"""Colonist Ruins -- Hub 5 exterior zone

A restrained, grief-forward ruin zone about occupation, extraction, memory, and careful return rather than treasure-hunting spectacle."""

from world.area_builder import AreaBuilder


def build():
    area = AreaBuilder('colonist_ruins')

    area.zone(
        name='Colonist Ruins',
        zone_type='frontier',
        continent='veluana',
        tier=5,
        region='veluana_archipelago',
        hub_city='korahei',
        faction_territory='contested',
        faction_presence=['kauroran', 'raider', 'consortium'],
        world_x=72,
        world_y=-13,
        world_radius=135,
    )

    area.material('reef_silverjack', tier=1, terrain='water', absorbed_property='finesse', profession_bonus={'cooking': 0.1, 'fishing': 0.05})
    area.material('tide_eel', tier=2, terrain='water', absorbed_property='timing', profession_bonus={'cooking': 0.1, 'alchemy': 0.05})
    area.material('saltfruit', tier=1, terrain='coastal', absorbed_property='endurance', profession_bonus={'cooking': 0.1})
    area.material('hearthroot', tier=2, terrain='garden', absorbed_property='warmth', profession_bonus={'cooking': 0.1, 'alchemy': 0.05})
    area.material('tide_mint', tier=1, terrain='water', absorbed_property='cooling', profession_bonus={'alchemy': 0.1, 'cooking': 0.05})
    area.material('blackglass_shard', tier=2, terrain='ruins', absorbed_property='edge', profession_bonus={'smithing': 0.1, 'scholarship': 0.05})
    area.material('reefcrawler_shell', tier=1, terrain='reef', absorbed_property='protection', profession_bonus={'smithing': 0.1})
    area.material('saltpalm_wood', tier=1, terrain='coastal', absorbed_property='flexibility', profession_bonus={'engineering': 0.1})

    # Rooms
    ld_quiet_landing = area.room('ld_quiet_landing', name='Quiet Landing', desc='The southern boat grounds on a shore of broken pilings, salt-split beams, and careful warning cord. This is not a treasure beach; it is the first threshold into grief, hazard, and history.', room_type='ruins')
    ld_broken_dock = area.room('ld_broken_dock', name='Broken Dock', desc='The broken dock leans into the tide with iron staples still biting the old wood. New warning cords stand beside old extraction scars, making care and harm visible in the same glance.', room_type='ruins')
    ld_salt_split_beam = area.room('ld_salt_split_beam', name='Salt-Split Beam', desc='A saltpalm beam lies split where an imported pier once forced the shoreline straight. Fresh-cut notches mark the sound lengths Kau’roran crews may recover after the tide turns, while the rest remains braced against the wash.', room_type='ruins')
    ld_warning_cord_pile = area.room('ld_warning_cord_pile', name='Warning Cord Pile', desc='Coils of red and sea-green warning cord rest in a lidded basket above the spray. Knots retired from repaired hazards remain tied to their dated slats, leaving a plain record of which routes have changed since yesterday.', room_type='ruins')
    ld_imported_paving_crack = area.room('ld_imported_paving_crack', name='Imported Paving Crack', desc='Square paving stones stop abruptly at a fracture widened by saltfruit roots. Small shell markers distinguish ripe stems cleared for harvest from new growth being left to bind the disturbed soil.', room_type='ruins')
    ld_offering_above_surf = area.room('ld_offering_above_surf', name='Offering Above Surf', desc='A narrow shelf above the highest tide holds bread crusts, folded leaves, and bowls turned against the rain. Nothing identifies whom they honor; a clean arc of swept stone asks passing hands to leave that privacy intact.', room_type='ruins')
    ld_jackal_track_sand = area.room('ld_jackal_track_sand', name='Jackal Track Sand', desc='Jackal tracks cross the landing sand between warped planks and washed debris. The animals follow shelter and scraps, so clearing them protects visitors without pretending the ruins are only hostile.', room_type='ruins')
    ld_old_iron_staple = area.room('ld_old_iron_staple', name='Old Iron Staple', desc='An iron staple as broad as a hand pins nothing now, but rust stains trace the vanished dock timbers across the stone. A newer cord keeps feet clear without hiding the scale of what was built here to move cargo inland.', room_type='ruins')
    ld_low_wreck_shade = area.room('ld_low_wreck_shade', name='Low Wreck Shade', desc='The upturned ribs of a small workboat cast shade over a tide pocket where silverjack shelter. A woven tally hangs from the nearest rib, showing which catches the landing kitchen took and when the pool should be left alone.', room_type='ruins')
    ld_quiet_rope_post = area.room('ld_quiet_rope_post', name='Quiet Rope Post', desc='A quiet rope post marks where boats tie off before entering the ruin lanes. Jackals nose under the wreck shade nearby, drawn by offerings left too low and meals dropped by nervous hands.', room_type='ruins')
    ld_tide_bent_nail = area.room('ld_tide_bent_nail', name='Tide-Bent Nail', desc='A bent nail protrudes from a piling at shin height, wrapped in bright fiber after the last storm exposed it. Beside it, three wet knots on the guide cord warn that the lower stones disappear before the incoming tide looks dangerous.', room_type='ruins')
    ld_landing_rubble_shelf = area.room('ld_landing_rubble_shelf', name='Landing Rubble Shelf', desc='Storm-thrown masonry has been sorted into a low shelf: stable footing to one side, recorded occupation fragments to the other. Rain has blurred the oldest chalk marks, and a covered slate waits for the next patrol to renew them.', room_type='ruins')
    ld_broken_cargo_stone = area.room('ld_broken_cargo_stone', name='Broken Cargo Stone', desc='A cargo stone has cracked through its carved weight line, exposing a channel worn by years of rope. Shell counters set along the groove make the old measuring system readable without lifting the stone from the shore.', room_type='ruins')
    ld_mended_warning_board = area.room('ld_mended_warning_board', name='Mended Warning Board', desc='Saltpalm splints hold together a warning board whose oldest face was burned away. Its replaceable slats list today’s unstable wall, jackal shelter, and safe return tide in fresh charcoal rather than pretending the route stays fixed.', room_type='ruins')
    ld_south_debris_turn = area.room('ld_south_debris_turn', name='South Debris Turn', desc='The south turn bends around cargo stone, blackglass chips, and a windbreak made from old beams. Jackals use the clutter as cover, making the first combat loop a matter of clearing passage.', room_type='ruins')
    ld_blackglass_chip_sand = area.room('ld_blackglass_chip_sand', name='Blackglass Chip Sand', desc='Blackglass chips gleam among pale grains where a cargo jar shattered long ago. The sharpest pieces sit inside a marked sieve for the ruin keepers to catalogue; wave-rounded fragments remain in place, showing how far the spill has traveled.', room_type='ruins')
    ld_old_boat_scar = area.room('ld_old_boat_scar', name='Old Boat Scar', desc='Parallel grooves climb the beach where heavy boats were once dragged beyond the tide. Recent skiff marks cross them lightly, each paired with a shell token that lets the watch account for crews still inside the ruins.', room_type='ruins')
    ld_salt_warped_plank = area.room('ld_salt_warped_plank', name='Salt-Warped Plank', desc='A warped plank bridges a drainage cut only at low water, its repaired end stamped with the current patrol knot. Darkening salt lines beneath it preserve the heights of earlier surges and make the next safe crossing a matter of evidence.', room_type='ruins')
    ld_shore_ruin_mouth = area.room('ld_shore_ruin_mouth', name='Shore Ruin Mouth', desc='Burned stone closes around the shore path, muting surf and conversation alike. A braided threshold cord leaves one deliberate gap; beyond it, visitors enter on Kau’roran terms of witness, restraint, and return.', room_type='ruins')
    ld_last_landing_stone = area.room('ld_last_landing_stone', name='Last Landing Stone', desc='The final landing stone carries old wheel wear beneath fresher jackal tracks. Patrol marks point north toward the tended square and back toward the tide board, keeping both the reason for entering and the way home in view.', room_type='ruins')
    gr_grief_square = area.room('gr_grief_square', name='Grief Square', desc='Kau’roran hands have turned an old victory square inward, toward names, water bowls, shared shade, and room for silence. Fresh sweep lines and changing offerings make remembrance visible as present work rather than an abandoned monument.', room_type='ruins')
    gr_pried_plaque_wall = area.room('gr_pried_plaque_wall', name='Pried Plaque Wall', desc='Rectangular scars show where occupation plaques were removed without smoothing away their grip on the wall. Small name slates now rest between the marks, each hung on cord so families can revise, relocate, or withdraw it.', room_type='ruins')
    gr_plain_bowl_row = area.room('gr_plain_bowl_row', name='Plain Bowl Row', desc='A row of unmatched bowls holds water, flowers, polished shell, or nothing at all. Cleaning pegs separate vessels still being tended from those ready to return to common use, keeping absence from becoming neglect.', room_type='ruins')
    gr_recarved_name_seat = area.room('gr_recarved_name_seat', name='Recarved Name Seat', desc='A broad stone seat bears a name recut after the occupation inscription beneath it was removed. The older groove remains visible at the edge, while a family knot marks who authorized the newer words.', room_type='ruins')
    gr_warm_hearthroot_crack = area.room('gr_warm_hearthroot_crack', name='Warm Hearthroot Crack', desc='Hearthroot thrives in a sun-warmed fracture where ash and shell compost collect. Harvest cords rotate among mature clusters, leaving flowering stems for the square’s cooks and the next season’s growth.', room_type='ruins')
    gr_inward_mourner_bench = area.room('gr_inward_mourner_bench', name='Inward Mourner Bench', desc='A curved bench faces the square’s quiet center rather than any speaker’s platform. One end is raised, the other left open beside a steadying rail, and woven screens can narrow the space when grief asks for privacy.', room_type='ruins')
    gr_empty_window_breath = area.room('gr_empty_window_breath', name='Empty Window Breath', desc='Sea wind passes through an empty window and stirs the offering cords without lifting the name slates. Caretakers adjust a reed baffle after storms, preserving air and sound while protecting the more fragile remembrances.', room_type='ruins')
    gr_low_truth_step = area.room('gr_low_truth_step', name='Low Truth Step', desc='A low step holds witness knots from accounts shared here and blank cord for accounts not yet offered. Nothing records the words themselves; the knots honor that testimony occurred without making private truth public property.', room_type='ruins')
    gr_ash_touched_corner = area.room('gr_ash_touched_corner', name='Ash-Touched Corner', desc='Fire-dark stone survives in a sheltered corner beside a tray of loose soil from the square’s renewal beds. A boundary of white shells keeps sweeping and sampling away from the ash until the keepers decide what care it needs.', room_type='ruins')
    gr_old_banner_socket = area.room('gr_old_banner_socket', name='Old Banner Socket', desc='An iron socket remains where a conquest banner once stood above the square. It holds no replacement flag; rainwater and fallen petals collect in the hollow, keeping the absence deliberate and maintained.', room_type='ruins')
    gr_quiet_center_stone = area.room('gr_quiet_center_stone', name='Quiet Center Stone', desc='A flat center stone anchors circles of seats, mats, and open floor without elevating any one place. Chalk arcs change with family gatherings and public remembrances, then wash clean for the next arrangement.', room_type='ruins')
    gr_broken_speech_dais = area.room('gr_broken_speech_dais', name='Broken Speech Dais', desc='The old speech dais has been lowered into three broad steps, its formal front cracked and reused as seating. Spoken names can move through the circle now without granting a single voice the architecture of command.', room_type='ruins')
    gr_water_bowl_shade = area.room('gr_water_bowl_shade', name='Water Bowl Shade', desc='A patched canopy shades drinking water and smaller bowls used to bead weathered names. Refill marks show what is safe to drink and what touched the wall, while the latest inspection knot records the morning’s care.', room_type='ruins')
    gr_soft_name_wall = area.room('gr_soft_name_wall', name='Soft Name Wall', desc='Limewash creates a soft writing surface for names awaiting durable form. Rain fades the oldest charcoal first, and dated copies kept under the eave let families choose renewal, correction, or release.', room_type='ruins')
    gr_grief_mat_niche = area.room('gr_grief_mat_niche', name='Grief Mat Niche', desc='Rolled mats of several lengths fill a dry niche beside cedar blocks and back rests. Damp tags move used pieces to the airing line, making bodily comfort and the work of receiving the next mourner equally visible.', room_type='ruins')
    gr_unclaimed_trophy_base = area.room('gr_unclaimed_trophy_base', name='Unclaimed Trophy Base', desc='A bare plinth keeps the bolt pattern of a removed occupation trophy. No new figure claims the height; small bowls circle its foot, shifting attention from conquest above to people remembered together below.', room_type='ruins')
    gr_wind_hole_walk = area.room('gr_wind_hole_walk', name='Wind-Hole Walk', desc='Openings in the ruined wall make this walk loud with surf in one weather and nearly still in another. Colored ties identify the quieter turns each day, giving private conversations a route that changes with the wind.', room_type='ruins')
    gr_southern_memory_seat = area.room('gr_southern_memory_seat', name='Southern Memory Seat', desc='A south-facing seat looks back along the landing where supply skiffs and returning patrols appear. Route knots left beneath its arm connect remembrance to the people who keep arriving with water, bread, records, and news.', room_type='ruins')
    gr_square_of_returned_names = area.room('gr_square_of_returned_names', name='Square of Returned Names', desc='Recently returned names hang at human height beneath a plain shelter before joining the older walls. Family cords, archive marks, and empty pegs show that each arrival follows a different path—and that more may still come.', room_type='ruins')
    gr_last_bowl_ledge = area.room('gr_last_bowl_ledge', name='Last Bowl Ledge', desc='The ledge nearest the archive holds the latest bowl placed in the square, distinguished only by an unfaded reed tie. Older ties move onward as care continues, so “last” remains a changing place in an unfinished procession.', room_type='ruins')
    ar_archive_shell = area.room('ar_archive_shell', name='Archive Shell', desc='The roofless archive holds brittle shelves, burnt ledgers, and fragments someone tried to erase. Clean shells weigh down paper scraps so the work stays about memory, not salvage value.', room_type='building')
    ar_charred_shelf_groove = area.room('ar_charred_shelf_groove', name='Charred Shelf Groove', desc='Charred grooves divide the wall into the narrow measures of vanished ledger shelves. Caretakers have threaded pale cord through surviving brackets, reconnecting fragments whose dates and cargo tallies once occupied the same run.', room_type='building')
    ar_shell_weighted_scrap = area.room('ar_shell_weighted_scrap', name='Shell-Weighted Scrap', desc='Clean shells hold a fan of paper scraps against the sea wind, each shell painted with the fragment’s current review mark. New matches move inward toward the copying tables; uncertain pieces remain here rather than being forced into a convenient story.', room_type='building')
    ar_blackglass_sliver_desk = area.room('ar_blackglass_sliver_desk', name='Blackglass Sliver Desk', desc='Blackglass slivers catch light across a desk where ledgers once sorted lives into cargo. Looters pry here because the fragments sell, while caretakers return because the names matter.', room_type='building')
    ar_salt_curled_page = area.room('ar_salt_curled_page', name='Salt-Curled Page', desc='A salt-curled page rests inside a reed frame that never quite presses it flat. Ink emerges and retreats with the damp, so a slate beside it records readings by weather instead of treating any single glimpse as final.', room_type='building')
    ar_name_sorted_fragment = area.room('ar_name_sorted_fragment', name='Name-Sorted Fragment', desc='Fragments bearing the same half-name share a cloth pocket, though three differently colored ties preserve competing readings. A blank tie waits for testimony from Korahei, allowing living memory to correct the archive rather than submit to it.', room_type='building')
    ar_broken_index_wall = area.room('ar_broken_index_wall', name='Broken Index Wall', desc='Empty peg holes reveal an index once arranged by shipment, labor allotment, and penalty. Evi’s removable tags map those categories without restoring their authority, tracing where personal names were reduced to entries in the occupation’s system.', room_type='building')
    ar_ledger_ash_niche = area.room('ar_ledger_ash_niche', name='Ledger Ash Niche', desc='Ledger ash gathers in a niche protected from wind by collapsed shelves. Scavengers probe the grey dust for seals and metal, turning archive defense into preservation rather than treasure hunting.', room_type='building')
    ar_roofless_reading_table = area.room('ar_roofless_reading_table', name='Roofless Reading Table', desc='A broad reading table stands beneath a canopy that can be lowered before rain. Stone cups hold today’s sequence of fragments, and an empty cup at the end reserves space for whatever the next careful comparison changes.', room_type='building')
    ar_old_seal_floor = area.room('ar_old_seal_floor', name='Old Seal Floor', desc='Pressed into the floor tiles are wax traces from offices that certified seizures and shipments. Thin paper rubbings capture the changing pattern of seals while leaving every stain where Kau’roran keepers found it.', room_type='building')
    ar_torn_charter_rack = area.room('ar_torn_charter_rack', name='Torn Charter Rack', desc='Iron clips line a rack built for colonial charters; most hold only burned corners or the clean shapes of missing sheets. A chalk key links surviving clauses to the yard machinery they authorized, making administrative harm visible beyond the signatures.', room_type='building')
    ar_quiet_copy_bench = area.room('ar_quiet_copy_bench', name='Quiet Copy Bench', desc='Reed pens, scrap slates, and drying weights occupy a bench set apart from the originals. Every copy begins with its fragment mark and the copier’s knot, preserving uncertainty and a route back when another reading proves better.', room_type='building')
    ar_ink_salt_basin = area.room('ar_ink_salt_basin', name='Ink Salt Basin', desc='Black ink has crystallized around a shallow stone basin once used by archive clerks. Caretakers test rinse water on detached soot nearby, logging what fades, what returns, and what must not touch the surviving pages.', room_type='building')
    ar_collapsed_stack_lane = area.room('ar_collapsed_stack_lane', name='Collapsed Stack Lane', desc='A fallen stack divides the lane into braced and unexamined sections. Numbered wedges record each safe lift, while dust patterns beyond the last brace show that the recovery remains unfinished and should not be rushed.', room_type='building')
    ar_mended_record_mat = area.room('ar_mended_record_mat', name='Mended Record Mat', desc='A patched mat displays records whose edges now join without paste. Shells mark confirmed names, charcoal marks disputed dates, and open spaces keep each reconstruction provisional enough to change with new evidence.', room_type='building')
    ar_north_archive_door = area.room('ar_north_archive_door', name='North Archive Door', desc='The north doorway opens toward the burnt names wall, with a reed screen ready to block sudden rain. A transfer slate counts fragments entering and copies leaving, ensuring that archive work returns knowledge to the people named beyond it.', room_type='building')
    ar_brittle_page_alcove = area.room('ar_brittle_page_alcove', name='Brittle Page Alcove', desc='The driest alcove shelters pages too brittle for the open tables. Their reed boxes carry no sale value or collector’s title—only place found, hands consulted, and the next condition Evi means to check.', room_type='building')
    ar_readers_caution_step = area.room('ar_readers_caution_step', name="Reader's Caution Step", desc="The reader's step creaks under salt-curled paper and broken tile. Evi's caution marks show where to stand, and looter cuts show why knowledge in the open still needs guarding.", room_type='building')
    ar_last_ledger_shade = area.room('ar_last_ledger_shade', name='Last Ledger Shade', desc='One ledger remains bound beneath a slant of surviving roof, its outer leaves blackened and its center unread. A rotating watch record notes heat, damp, insects, and attempted tampering, turning preservation into daily work rather than a finished display.', room_type='building')
    ar_archive_exit_crack = area.room('ar_archive_exit_crack', name='Archive Exit Crack', desc='A fire crack runs from the archive floor toward the wall of names outside. Copied fragments travel that line in closed reed cases, accompanied by a spoken name when known and silence when the record has not earned one yet.', room_type='building')
    bn_burnt_names = area.room('bn_burnt_names', name='Burnt Names', desc='A charcoal-dark wall bears names the fire broke and Kau’roran hands have patiently returned. Water beads in some strokes, research ties wait beside others, and untouched gaps hold space for people whose truth is not ready to be carved.', room_type='ruins')
    bn_pale_recut_letter = area.room('bn_pale_recut_letter', name='Pale Recut Letter', desc='One pale letter has been recut beside its scorched original rather than over it. The paired marks preserve both the damage and the later testimony that restored this much of the name.', room_type='ruins')
    bn_water_beaded_stroke = area.room('bn_water_beaded_stroke', name='Water-Beaded Stroke', desc='Fresh water gathers in a shallow carved stroke, briefly darkening the surviving line enough to read. A nearby cup is covered between use, and a shell tally records which names were tended before the stone dries again.', room_type='ruins')
    bn_research_cloth_tie = area.room('bn_research_cloth_tie', name='Research Cloth Tie', desc='Cloth ties hang from pegs beside uncertain names: blue for a remembered sound, ochre for an archive fragment, and uncolored fiber for a family answer still awaited. None is a claim to finish the carving without consent.', room_type='ruins')
    bn_looters_edge_scratch = area.room('bn_looters_edge_scratch', name="Looter's Edge Scratch", desc='Scratches scar the edge of the name wall where looters tested the stone and stopped short of the center. The damage is small enough to miss and ugly enough to explain why watchers remain.', room_type='ruins')
    bn_sunset_reading_stone = area.room('bn_sunset_reading_stone', name='Sunset Reading Stone', desc='At sunset, low light catches strokes invisible at noon and throws newer cuts into relief. Readers leave dated charcoal impressions on loose slate, letting tomorrow’s comparison challenge what evening seemed to reveal.', room_type='ruins')
    bn_charcoal_name_wall = area.room('bn_charcoal_name_wall', name='Charcoal Name Wall', desc='Soot lies deepest where rows of names once continued behind a collapsed facing. Pale guide marks stop short of the black stone, showing where keepers know a line belongs but refuse to invent the letters.', room_type='ruins')
    bn_soft_repair_line = area.room('bn_soft_repair_line', name='Soft Repair Line', desc='A seam of soft lime and crushed shell supports a fractured row without sealing it permanently. Small date pegs show each adjustment, so later hands can reverse a repair if stone or testimony shifts the reading.', room_type='ruins')
    bn_unfinished_name_gap = area.room('bn_unfinished_name_gap', name='Unfinished Name Gap', desc='An unfinished gap waits among the recut names, tied with cloth for research still underway. Jackals and scavengers both cross this edge, so protecting the gap protects a future answer.', room_type='ruins')
    bn_low_offering_stone = area.room('bn_low_offering_stone', name='Low Offering Stone', desc='A low stone holds first bites of bread, saltfruit peel, and folded leaves beneath the names. Older offerings are gathered before they spoil and returned to the garden soil, keeping remembrance generous without feeding the jackals.', room_type='ruins')
    bn_ash_warm_corner = area.room('bn_ash_warm_corner', name='Ash-Warm Corner', desc='Morning sun warms a corner where ash remains fused into the wall. A reed screen can shade the fragile surface by midday, and its position log gives the watch another ordinary duty of care.', room_type='ruins')
    bn_quiet_witness_rail = area.room('bn_quiet_witness_rail', name='Quiet Witness Rail', desc='A smooth rail offers support at standing and seated height without facing anyone toward an audience. Worn grips and newly wrapped sections show how many kinds of bodies have paused here, and how the site adapts to receive them.', room_type='ruins')
    bn_returned_syllable_seat = area.room('bn_returned_syllable_seat', name='Returned Syllable Seat', desc='A curved seat faces a name whose middle syllable was restored from three family recollections. Their distinct witness knots remain beneath the carving, honoring agreement without erasing the separate voices that reached it.', room_type='ruins')
    bn_name_water_jar = area.room('bn_name_water_jar', name='Name Water Jar', desc='A plain water jar rests beside repaired syllables so visitors can bead the letters before reading. The jar also marks where looters cut through after dark, making vigilance part of remembrance.', room_type='ruins')
    bn_mended_letter_shelf = area.room('bn_mended_letter_shelf', name='Mended Letter Shelf', desc='Practice stones line a shallow shelf below one difficult repaired letter. Earlier attempts remain beside the accepted form, making recovery visible as patient work rather than a flawless act by a single hand.', room_type='ruins')
    bn_west_burn_scar = area.room('bn_west_burn_scar', name='West Burn Scar', desc='The western face is blistered more deeply than the rest, but wind, fuel, and intent cannot yet be separated from the mark. Keepers have framed the scar without labeling its cause, preserving evidence where certainty would only flatter the teller.', room_type='ruins')
    bn_deep_soot_niche = area.room('bn_deep_soot_niche', name='Deep Soot Niche', desc='Protected soot fills a niche no rain has reached. Tiny sampling squares are numbered and few; most of the deposit remains untouched while archive notes track what each careful test can actually support.', room_type='ruins')
    bn_last_recut_name = area.room('bn_last_recut_name', name='Last Recut Name', desc='The most recently returned name carries a fresh date peg and a loose wreath not yet faded by salt air. Space beside it makes “last” a statement about today, not an end to the wall’s unfinished work.', room_type='ruins')
    bn_wall_of_still_names = area.room('bn_wall_of_still_names', name='Wall of Still Names', desc='Several names remain clear but unvoiced, marked by closed cloth loops requested by those who remember them. The writing may be witnessed; the stories attached to it are not owed to every visitor.', room_type='ruins')
    bn_silent_end_stone = area.room('bn_silent_end_stone', name='Silent End Stone', desc='An uncarved stone closes the name wall before the path reaches the old works. Its clean surface offers no summary, leaving the preserved names—and the extraction system ahead—to stand in relation without turning either into spectacle.', room_type='ruins')
    cw_charter_works_gate = area.room('cw_charter_works_gate', name='Charter Works Gate', desc='Beyond the name wall, a wide gate frames the occupation’s workshops as one connected machine: counting yard, scale house, ramp, and cargo track. Kau’roran guide cords lead through the evidence without restoring the old flow of labor.', room_type='ruins')
    cw_foreign_weight_table = area.room('cw_foreign_weight_table', name='Foreign Weight Table', desc='Stone and iron weights crowd a table, all stamped to an imported measure and several hollowed beneath. Caretakers have paired each with a true shell counter, exposing how official numbers made unequal exchange appear exact.', room_type='ruins')
    cw_empty_tool_rack = area.room('cw_empty_tool_rack', name='Empty Tool Rack', desc='An empty rack still bears outlines for picks, tongs, and cutting bars, with smaller personal marks scratched below the numbered slots. Cloth tabs connect some marks to recovered names; the rest remain evidence of workers the inventory never recorded.', room_type='ruins')
    cw_cracked_wash_trough = area.room('cw_cracked_wash_trough', name='Cracked Wash Trough', desc='A stone trough split by salt now catches clean rain instead of washing ore. Tide mint grows along the outflow, and harvest markers protect young runners where their roots slow contaminated grit from reaching the shore.', room_type='ruins')
    cw_loot_pried_metal = area.room('cw_loot_pried_metal', name='Loot-Pried Metal', desc='Fresh pry marks shine on metal locals left in place as evidence. Fighting here is not about defending junk; it is about stopping someone from selling the proof piece by piece.', room_type='ruins')
    cw_counting_yard_line = area.room('cw_counting_yard_line', name='Counting Yard Line', desc='Parallel white lines divide the yard into narrow waiting lanes, each terminating at the same clerk’s plinth used for cargo totals. Worn heel hollows continue where wheel ruts stop, revealing whose movement the layout measured and controlled.', room_type='ruins')
    cw_old_contract_stone = area.room('cw_old_contract_stone', name='Old Contract Stone', desc='A contract was chiseled into stone where refusal could not alter its terms. Removable translations distinguish promised rations from penalties added in smaller script, while open space invites corrections from family memory and archive fragments.', room_type='ruins')
    cw_broken_pulley_frame = area.room('cw_broken_pulley_frame', name='Broken Pulley Frame', desc='A timber frame spans the yard with one pulley split and the other seized by salt. Rope angles drawn on a ground slate reconstruct how loads moved from wash trough to scale without asking anyone to operate the dangerous remains.', room_type='ruins')
    cw_rope_burn_post = area.room('cw_rope_burn_post', name='Rope-Burn Post', desc='Rope burns blacken a post near the old extraction ramp, close enough to the yard lines to make counting bodies feel bureaucratic. Looters shelter there because the history still has hardware to steal.', room_type='ruins')
    cw_extraction_ramp = area.room('cw_extraction_ramp', name='Extraction Ramp', desc='Deep wheel grooves descend a ramp whose center is polished by bare feet rather than carts. New crossbars prevent rolling debris, and each repair bears a patrol date so the route’s present safety never obscures what its old efficiency demanded.', room_type='ruins')
    cw_dry_scale_house = area.room('cw_dry_scale_house', name='Dry Scale House', desc='The scale house roof survives, preserving balance beams, tariff pegs, and a clerk’s viewing slit above the yard. Comparative weights sit behind cord where changing humidity is logged before anyone draws conclusions from their unequal balance.', room_type='ruins')
    cw_work_bell_socket = area.room('cw_work_bell_socket', name='Work Bell Socket', desc='Four bolt holes mark where a bell governed waking, hauling, and stopping from one central post. The bell is gone; family accounts tied around the socket remember different schedules, refusing to let its missing voice simplify the days it controlled.', room_type='ruins')
    cw_split_ledger_yard = area.room('cw_split_ledger_yard', name='Split Ledger Yard', desc='Two ledger fragments disagree across a sheltered yard: one counts blackglass weight, the other rations issued to numbered crews. Moveable counters reveal gaps between production and provision, with every reconstruction dated for later challenge.', room_type='ruins')
    cw_salt_cracked_trough = area.room('cw_salt_cracked_trough', name='Salt-Cracked Trough', desc='Salt crystals lift the lip of a second wash trough around a dense bed of tide mint. Gatherers use woven dividers to take mature stems from alternating sections, leaving roots that filter the old yard runoff.', room_type='ruins')
    cw_blackglass_sorting_mat = area.room('cw_blackglass_sorting_mat', name='Blackglass Sorting Mat', desc='A new sorting mat covers the footprint of the old weighing station, separating loose blackglass by danger and provenance rather than price. Harvest-safe shards receive shell tags; embedded pieces and catalogued evidence remain under watch from looters who would erase that distinction.', room_type='ruins')
    cw_unpaid_labor_gate = area.room('cw_unpaid_labor_gate', name='Unpaid Labor Gate', desc='A narrow gate funnels the yard past token hooks and a penalty board, though no wage counter stands nearby. Returned names now hang beside surviving crew numbers, joining personal testimony to the architecture that treated labor as a debt.', room_type='ruins')
    cw_fallen_beam_office = area.room('cw_fallen_beam_office', name='Fallen Beam Office', desc='A saltpalm roof beam has fallen across the overseer’s office, exposing dispatch marks beneath its painted face. Kau’roran crews mark only storm-loosened lengths for recovery, leaving the supported span and its evidence in place.', room_type='ruins')
    cw_low_cargo_slot = area.room('cw_low_cargo_slot', name='Low Cargo Slot', desc='A low slot connects the office to the outbound track, wide enough for bundled material but not an upright person. Finger wear on the inner sill and order marks outside show how cargo movement concealed human handling behind a wall.', room_type='ruins')
    cw_last_charter_mark = area.room('cw_last_charter_mark', name='Last Charter Mark', desc='The latest dated charter mark ends midway through a row, followed by hammer scars that strike across its seal. A protective frame preserves both official claim and interruption, while archive ties leave the identity of the resisting hands unresolved.', room_type='ruins')
    cw_works_exit_track = area.room('cw_works_exit_track', name='Works Exit Track', desc='Cargo ruts leave the works and fade beneath saltgrass, but today’s patrol prints return toward the names wall and landing. A route slate records erosion, looter sign, and recovered evidence, turning the old outbound track into a cycle of watch and return.', room_type='ruins')

    # Local exits
    area.exit(ld_quiet_landing, ld_broken_dock, 'east')
    area.exit(ld_broken_dock, ld_quiet_landing, 'west')
    area.exit(ld_broken_dock, ld_salt_split_beam, 'east')
    area.exit(ld_salt_split_beam, ld_broken_dock, 'west')
    area.exit(ld_salt_split_beam, ld_warning_cord_pile, 'east')
    area.exit(ld_warning_cord_pile, ld_salt_split_beam, 'west')
    area.exit(ld_warning_cord_pile, ld_imported_paving_crack, 'east')
    area.exit(ld_imported_paving_crack, ld_warning_cord_pile, 'west')
    area.exit(ld_imported_paving_crack, ld_offering_above_surf, 'east')
    area.exit(ld_offering_above_surf, ld_imported_paving_crack, 'west')
    area.exit(ld_offering_above_surf, ld_jackal_track_sand, 'east')
    area.exit(ld_jackal_track_sand, ld_offering_above_surf, 'west')
    area.exit(ld_jackal_track_sand, ld_old_iron_staple, 'east')
    area.exit(ld_old_iron_staple, ld_jackal_track_sand, 'west')
    area.exit(ld_old_iron_staple, ld_low_wreck_shade, 'east')
    area.exit(ld_low_wreck_shade, ld_old_iron_staple, 'west')
    area.exit(ld_low_wreck_shade, ld_quiet_rope_post, 'east')
    area.exit(ld_quiet_rope_post, ld_low_wreck_shade, 'west')
    area.exit(ld_quiet_rope_post, ld_tide_bent_nail, 'east')
    area.exit(ld_tide_bent_nail, ld_quiet_rope_post, 'west')
    area.exit(ld_tide_bent_nail, ld_landing_rubble_shelf, 'east')
    area.exit(ld_landing_rubble_shelf, ld_tide_bent_nail, 'west')
    area.exit(ld_landing_rubble_shelf, ld_broken_cargo_stone, 'east')
    area.exit(ld_broken_cargo_stone, ld_landing_rubble_shelf, 'west')
    area.exit(ld_broken_cargo_stone, ld_mended_warning_board, 'east')
    area.exit(ld_mended_warning_board, ld_broken_cargo_stone, 'west')
    area.exit(ld_mended_warning_board, ld_south_debris_turn, 'east')
    area.exit(ld_south_debris_turn, ld_mended_warning_board, 'west')
    area.exit(ld_south_debris_turn, ld_blackglass_chip_sand, 'east')
    area.exit(ld_blackglass_chip_sand, ld_south_debris_turn, 'west')
    area.exit(ld_blackglass_chip_sand, ld_old_boat_scar, 'east')
    area.exit(ld_old_boat_scar, ld_blackglass_chip_sand, 'west')
    area.exit(ld_old_boat_scar, ld_salt_warped_plank, 'east')
    area.exit(ld_salt_warped_plank, ld_old_boat_scar, 'west')
    area.exit(ld_salt_warped_plank, ld_shore_ruin_mouth, 'east')
    area.exit(ld_shore_ruin_mouth, ld_salt_warped_plank, 'west')
    area.exit(ld_shore_ruin_mouth, ld_last_landing_stone, 'east')
    area.exit(ld_last_landing_stone, ld_shore_ruin_mouth, 'west')
    area.exit(gr_grief_square, gr_pried_plaque_wall, 'east')
    area.exit(gr_pried_plaque_wall, gr_grief_square, 'west')
    area.exit(gr_pried_plaque_wall, gr_plain_bowl_row, 'east')
    area.exit(gr_plain_bowl_row, gr_pried_plaque_wall, 'west')
    area.exit(gr_plain_bowl_row, gr_recarved_name_seat, 'east')
    area.exit(gr_recarved_name_seat, gr_plain_bowl_row, 'west')
    area.exit(gr_recarved_name_seat, gr_warm_hearthroot_crack, 'east')
    area.exit(gr_warm_hearthroot_crack, gr_recarved_name_seat, 'west')
    area.exit(gr_warm_hearthroot_crack, gr_inward_mourner_bench, 'east')
    area.exit(gr_inward_mourner_bench, gr_warm_hearthroot_crack, 'west')
    area.exit(gr_inward_mourner_bench, gr_empty_window_breath, 'east')
    area.exit(gr_empty_window_breath, gr_inward_mourner_bench, 'west')
    area.exit(gr_empty_window_breath, gr_low_truth_step, 'east')
    area.exit(gr_low_truth_step, gr_empty_window_breath, 'west')
    area.exit(gr_low_truth_step, gr_ash_touched_corner, 'east')
    area.exit(gr_ash_touched_corner, gr_low_truth_step, 'west')
    area.exit(gr_ash_touched_corner, gr_old_banner_socket, 'east')
    area.exit(gr_old_banner_socket, gr_ash_touched_corner, 'west')
    area.exit(gr_old_banner_socket, gr_quiet_center_stone, 'east')
    area.exit(gr_quiet_center_stone, gr_old_banner_socket, 'west')
    area.exit(gr_quiet_center_stone, gr_broken_speech_dais, 'east')
    area.exit(gr_broken_speech_dais, gr_quiet_center_stone, 'west')
    area.exit(gr_broken_speech_dais, gr_water_bowl_shade, 'east')
    area.exit(gr_water_bowl_shade, gr_broken_speech_dais, 'west')
    area.exit(gr_water_bowl_shade, gr_soft_name_wall, 'east')
    area.exit(gr_soft_name_wall, gr_water_bowl_shade, 'west')
    area.exit(gr_soft_name_wall, gr_grief_mat_niche, 'east')
    area.exit(gr_grief_mat_niche, gr_soft_name_wall, 'west')
    area.exit(gr_grief_mat_niche, gr_unclaimed_trophy_base, 'east')
    area.exit(gr_unclaimed_trophy_base, gr_grief_mat_niche, 'west')
    area.exit(gr_unclaimed_trophy_base, gr_wind_hole_walk, 'east')
    area.exit(gr_wind_hole_walk, gr_unclaimed_trophy_base, 'west')
    area.exit(gr_wind_hole_walk, gr_southern_memory_seat, 'east')
    area.exit(gr_southern_memory_seat, gr_wind_hole_walk, 'west')
    area.exit(gr_southern_memory_seat, gr_square_of_returned_names, 'east')
    area.exit(gr_square_of_returned_names, gr_southern_memory_seat, 'west')
    area.exit(gr_square_of_returned_names, gr_last_bowl_ledge, 'east')
    area.exit(gr_last_bowl_ledge, gr_square_of_returned_names, 'west')
    area.exit(ar_archive_shell, ar_charred_shelf_groove, 'east')
    area.exit(ar_charred_shelf_groove, ar_archive_shell, 'west')
    area.exit(ar_charred_shelf_groove, ar_shell_weighted_scrap, 'east')
    area.exit(ar_shell_weighted_scrap, ar_charred_shelf_groove, 'west')
    area.exit(ar_shell_weighted_scrap, ar_blackglass_sliver_desk, 'east')
    area.exit(ar_blackglass_sliver_desk, ar_shell_weighted_scrap, 'west')
    area.exit(ar_blackglass_sliver_desk, ar_salt_curled_page, 'east')
    area.exit(ar_salt_curled_page, ar_blackglass_sliver_desk, 'west')
    area.exit(ar_salt_curled_page, ar_name_sorted_fragment, 'east')
    area.exit(ar_name_sorted_fragment, ar_salt_curled_page, 'west')
    area.exit(ar_name_sorted_fragment, ar_broken_index_wall, 'east')
    area.exit(ar_broken_index_wall, ar_name_sorted_fragment, 'west')
    area.exit(ar_broken_index_wall, ar_ledger_ash_niche, 'east')
    area.exit(ar_ledger_ash_niche, ar_broken_index_wall, 'west')
    area.exit(ar_ledger_ash_niche, ar_roofless_reading_table, 'east')
    area.exit(ar_roofless_reading_table, ar_ledger_ash_niche, 'west')
    area.exit(ar_roofless_reading_table, ar_old_seal_floor, 'east')
    area.exit(ar_old_seal_floor, ar_roofless_reading_table, 'west')
    area.exit(ar_old_seal_floor, ar_torn_charter_rack, 'east')
    area.exit(ar_torn_charter_rack, ar_old_seal_floor, 'west')
    area.exit(ar_torn_charter_rack, ar_quiet_copy_bench, 'east')
    area.exit(ar_quiet_copy_bench, ar_torn_charter_rack, 'west')
    area.exit(ar_quiet_copy_bench, ar_ink_salt_basin, 'east')
    area.exit(ar_ink_salt_basin, ar_quiet_copy_bench, 'west')
    area.exit(ar_ink_salt_basin, ar_collapsed_stack_lane, 'east')
    area.exit(ar_collapsed_stack_lane, ar_ink_salt_basin, 'west')
    area.exit(ar_collapsed_stack_lane, ar_mended_record_mat, 'east')
    area.exit(ar_mended_record_mat, ar_collapsed_stack_lane, 'west')
    area.exit(ar_mended_record_mat, ar_north_archive_door, 'east')
    area.exit(ar_north_archive_door, ar_mended_record_mat, 'west')
    area.exit(ar_north_archive_door, ar_brittle_page_alcove, 'east')
    area.exit(ar_brittle_page_alcove, ar_north_archive_door, 'west')
    area.exit(ar_brittle_page_alcove, ar_readers_caution_step, 'east')
    area.exit(ar_readers_caution_step, ar_brittle_page_alcove, 'west')
    area.exit(ar_readers_caution_step, ar_last_ledger_shade, 'east')
    area.exit(ar_last_ledger_shade, ar_readers_caution_step, 'west')
    area.exit(ar_last_ledger_shade, ar_archive_exit_crack, 'east')
    area.exit(ar_archive_exit_crack, ar_last_ledger_shade, 'west')
    area.exit(bn_burnt_names, bn_pale_recut_letter, 'east')
    area.exit(bn_pale_recut_letter, bn_burnt_names, 'west')
    area.exit(bn_pale_recut_letter, bn_water_beaded_stroke, 'east')
    area.exit(bn_water_beaded_stroke, bn_pale_recut_letter, 'west')
    area.exit(bn_water_beaded_stroke, bn_research_cloth_tie, 'east')
    area.exit(bn_research_cloth_tie, bn_water_beaded_stroke, 'west')
    area.exit(bn_research_cloth_tie, bn_looters_edge_scratch, 'east')
    area.exit(bn_looters_edge_scratch, bn_research_cloth_tie, 'west')
    area.exit(bn_looters_edge_scratch, bn_sunset_reading_stone, 'east')
    area.exit(bn_sunset_reading_stone, bn_looters_edge_scratch, 'west')
    area.exit(bn_sunset_reading_stone, bn_charcoal_name_wall, 'east')
    area.exit(bn_charcoal_name_wall, bn_sunset_reading_stone, 'west')
    area.exit(bn_charcoal_name_wall, bn_soft_repair_line, 'east')
    area.exit(bn_soft_repair_line, bn_charcoal_name_wall, 'west')
    area.exit(bn_soft_repair_line, bn_unfinished_name_gap, 'east')
    area.exit(bn_unfinished_name_gap, bn_soft_repair_line, 'west')
    area.exit(bn_unfinished_name_gap, bn_low_offering_stone, 'east')
    area.exit(bn_low_offering_stone, bn_unfinished_name_gap, 'west')
    area.exit(bn_low_offering_stone, bn_ash_warm_corner, 'east')
    area.exit(bn_ash_warm_corner, bn_low_offering_stone, 'west')
    area.exit(bn_ash_warm_corner, bn_quiet_witness_rail, 'east')
    area.exit(bn_quiet_witness_rail, bn_ash_warm_corner, 'west')
    area.exit(bn_quiet_witness_rail, bn_returned_syllable_seat, 'east')
    area.exit(bn_returned_syllable_seat, bn_quiet_witness_rail, 'west')
    area.exit(bn_returned_syllable_seat, bn_name_water_jar, 'east')
    area.exit(bn_name_water_jar, bn_returned_syllable_seat, 'west')
    area.exit(bn_name_water_jar, bn_mended_letter_shelf, 'east')
    area.exit(bn_mended_letter_shelf, bn_name_water_jar, 'west')
    area.exit(bn_mended_letter_shelf, bn_west_burn_scar, 'east')
    area.exit(bn_west_burn_scar, bn_mended_letter_shelf, 'west')
    area.exit(bn_west_burn_scar, bn_deep_soot_niche, 'east')
    area.exit(bn_deep_soot_niche, bn_west_burn_scar, 'west')
    area.exit(bn_deep_soot_niche, bn_last_recut_name, 'east')
    area.exit(bn_last_recut_name, bn_deep_soot_niche, 'west')
    area.exit(bn_last_recut_name, bn_wall_of_still_names, 'east')
    area.exit(bn_wall_of_still_names, bn_last_recut_name, 'west')
    area.exit(bn_wall_of_still_names, bn_silent_end_stone, 'east')
    area.exit(bn_silent_end_stone, bn_wall_of_still_names, 'west')
    area.exit(cw_charter_works_gate, cw_foreign_weight_table, 'east')
    area.exit(cw_foreign_weight_table, cw_charter_works_gate, 'west')
    area.exit(cw_foreign_weight_table, cw_empty_tool_rack, 'east')
    area.exit(cw_empty_tool_rack, cw_foreign_weight_table, 'west')
    area.exit(cw_empty_tool_rack, cw_cracked_wash_trough, 'east')
    area.exit(cw_cracked_wash_trough, cw_empty_tool_rack, 'west')
    area.exit(cw_cracked_wash_trough, cw_loot_pried_metal, 'east')
    area.exit(cw_loot_pried_metal, cw_cracked_wash_trough, 'west')
    area.exit(cw_loot_pried_metal, cw_counting_yard_line, 'east')
    area.exit(cw_counting_yard_line, cw_loot_pried_metal, 'west')
    area.exit(cw_counting_yard_line, cw_old_contract_stone, 'east')
    area.exit(cw_old_contract_stone, cw_counting_yard_line, 'west')
    area.exit(cw_old_contract_stone, cw_broken_pulley_frame, 'east')
    area.exit(cw_broken_pulley_frame, cw_old_contract_stone, 'west')
    area.exit(cw_broken_pulley_frame, cw_rope_burn_post, 'east')
    area.exit(cw_rope_burn_post, cw_broken_pulley_frame, 'west')
    area.exit(cw_rope_burn_post, cw_extraction_ramp, 'east')
    area.exit(cw_extraction_ramp, cw_rope_burn_post, 'west')
    area.exit(cw_extraction_ramp, cw_dry_scale_house, 'east')
    area.exit(cw_dry_scale_house, cw_extraction_ramp, 'west')
    area.exit(cw_dry_scale_house, cw_work_bell_socket, 'east')
    area.exit(cw_work_bell_socket, cw_dry_scale_house, 'west')
    area.exit(cw_work_bell_socket, cw_split_ledger_yard, 'east')
    area.exit(cw_split_ledger_yard, cw_work_bell_socket, 'west')
    area.exit(cw_split_ledger_yard, cw_salt_cracked_trough, 'east')
    area.exit(cw_salt_cracked_trough, cw_split_ledger_yard, 'west')
    area.exit(cw_salt_cracked_trough, cw_blackglass_sorting_mat, 'east')
    area.exit(cw_blackglass_sorting_mat, cw_salt_cracked_trough, 'west')
    area.exit(cw_blackglass_sorting_mat, cw_unpaid_labor_gate, 'east')
    area.exit(cw_unpaid_labor_gate, cw_blackglass_sorting_mat, 'west')
    area.exit(cw_unpaid_labor_gate, cw_fallen_beam_office, 'east')
    area.exit(cw_fallen_beam_office, cw_unpaid_labor_gate, 'west')
    area.exit(cw_fallen_beam_office, cw_low_cargo_slot, 'east')
    area.exit(cw_low_cargo_slot, cw_fallen_beam_office, 'west')
    area.exit(cw_low_cargo_slot, cw_last_charter_mark, 'east')
    area.exit(cw_last_charter_mark, cw_low_cargo_slot, 'west')
    area.exit(cw_last_charter_mark, cw_works_exit_track, 'east')
    area.exit(cw_works_exit_track, cw_last_charter_mark, 'west')
    area.exit(ld_last_landing_stone, gr_grief_square, 'north')
    area.exit(gr_grief_square, ld_last_landing_stone, 'south')
    area.exit(gr_last_bowl_ledge, ar_archive_shell, 'north')
    area.exit(ar_archive_shell, gr_last_bowl_ledge, 'south')
    area.exit(ar_archive_exit_crack, bn_burnt_names, 'north')
    area.exit(bn_burnt_names, ar_archive_exit_crack, 'south')
    area.exit(bn_silent_end_stone, cw_charter_works_gate, 'north')
    area.exit(cw_charter_works_gate, bn_silent_end_stone, 'south')
    area.exit(ld_quiet_landing, 'korahei:qh_ruins_boat', 'north')

    # NPCs
    _ruin_listener = area.npc(gr_grief_square, 'npc_ruin_listener_ao', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Ruin Listener Ao studies you with open attention.'}, 'topics': {'help': 'Receives names before stories and stories before conclusions.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Ruin Listener Ao adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})
    _archive_evi = area.npc(ar_archive_shell, 'npc_archive_caretaker_evi', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Archive Caretaker Evi studies you with open attention.'}, 'topics': {'help': 'Sorts fragments by who they preserve, not what they sell for.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Archive Caretaker Evi adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})
    _bread_tahu = area.npc(ld_quiet_landing, 'npc_bread_runner_tahu', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Bread Runner Tahu studies you with open attention.'}, 'topics': {'help': 'Keeps ruin visits fed, practical, and human.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Bread Runner Tahu adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})

    # Quest and delivery item templates
    area.item('ruins_record_packet', key='unburned record packet', item_type='item', weight=0.2, rarity='normal', desc='A wrapped packet of fragments copied from the roofless archive.', value=0, is_quest_item=True)
    area.item('ruins_watch_bread', key="watcher's bread bundle", item_type='item', weight=0.5, rarity='normal', desc='A simple bundle of bread meant for people keeping vigil, not for ceremony.', value=0, is_quest_item=True)
    area.quest(
        'ruins_q_names_in_salt',
        name='Names in Salt',
        description='Ao asks you to witness the square and burnt names before handling records, making ruin exploration accountable to people.',
        quest_type='exploration',
        quest_giver='npc_ruin_listener_ao',
        objectives=[{'type': 'investigate', 'target': 'gr_grief_square', 'count': 1}, {'type': 'investigate', 'target': 'bn_burnt_names', 'count': 1}, {'type': 'talk_to', 'target': 'npc_archive_caretaker_evi', 'count': 1}],
        rewards=[{'action_type': 'give_scales', 'amount': 30}, {'action_type': 'give_skill_xp', 'skill_id': 'scholarship', 'count': 10}, {'action_type': 'modify_dimension', 'dimension': 'legacy', 'delta': 5, 'effect_id': 'ruins_q_names_in_salt:legacy', 'message': '|cThe names you witnessed become part of what you carry forward.|n'}],
        next_quest_id='ruins_q_unburned_records',
        prerequisite_quests=['kor_q_quiet_bowl'],
        can_share=True,
        consequence_small='Ao lays a new water bead at the names wall for your witness, making the archive work begin from remembrance.',
    )
    area.quest(
        'ruins_q_unburned_records',
        name='Unburned Records',
        description="Evi sends copied fragments back to Korahei's name-keeper, routing players home with context instead of sending them nowhere.",
        quest_type='delivery',
        quest_giver='npc_archive_caretaker_evi',
        objectives=[{'type': 'investigate', 'target': 'ar_archive_shell', 'count': 1}, {'type': 'deliver', 'target': 'npc_name_keeper_haoa', 'count': 1, 'item_tag': 'ruins_record_packet'}],
        rewards=[{'action_type': 'give_scales', 'amount': 34}, {'action_type': 'modify_standing', 'faction_id': 'kauroran', 'delta': 3500}],
        next_quest_id=None,
        prerequisite_quests=['ruins_q_names_in_salt'],
        can_share=True,
        consequence_small="Evi's copied fragments reach Haoa's keeping table, where names move from ruin debris back into Korahei's living memory.",
    )
    area.quest(
        'ruins_q_bread_for_watchers',
        name='Bread for the Watchers',
        description='Tahu asks you to carry food from the landing to Mareva, then return by seeing the grief square, making supply work emotional and navigational.',
        quest_type='delivery',
        quest_giver='npc_bread_runner_tahu',
        objectives=[{'type': 'investigate', 'target': 'gr_grief_square', 'count': 1}, {'type': 'deliver', 'target': 'npc_quiet_house_mareva', 'count': 1, 'item_tag': 'ruins_watch_bread'}],
        rewards=[{'action_type': 'give_scales', 'amount': 28}, {'action_type': 'give_skill_xp', 'skill_id': 'cooking', 'count': 8}],
        next_quest_id=None,
        prerequisite_quests=[],
        can_share=True,
        consequence_small='Tahu leaves watcher bread at the landing with your route knot on it, so supply work points visitors toward the grief square first.',
    )

    # Spawns
    area.spawn(ld_jackal_track_sand, 'ruin_jackal', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(ld_quiet_rope_post, 'ruin_jackal', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(ld_south_debris_turn, 'ruin_jackal', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(cw_loot_pried_metal, 'charter_looter', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(cw_rope_burn_post, 'charter_looter', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(cw_blackglass_sorting_mat, 'charter_looter', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(ar_blackglass_sliver_desk, 'charter_looter', count_min=1, count_max=1, respawn_minutes=18)
    area.spawn(ar_ledger_ash_niche, 'charter_looter', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(ar_readers_caution_step, 'charter_looter', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(bn_looters_edge_scratch, 'ruin_jackal', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(bn_unfinished_name_gap, 'ruin_jackal', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(bn_name_water_jar, 'charter_looter', count_min=1, count_max=2, respawn_minutes=18)

    # Gathering pools
    area.gathering_pool('fish', ['ld_quiet_landing', 'ld_low_wreck_shade'], ['reef_silverjack', 'tide_eel'], max_active=3, respawn_minutes=12)
    area.gathering_pool('forage', ['gr_warm_hearthroot_crack', 'ld_imported_paving_crack'], ['hearthroot', 'saltfruit'], max_active=3, respawn_minutes=12)
    area.gathering_pool('herb', ['cw_cracked_wash_trough', 'cw_salt_cracked_trough'], ['tide_mint'], max_active=3, respawn_minutes=12)
    area.gathering_pool('ore', ['ar_blackglass_sliver_desk', 'cw_blackglass_sorting_mat'], ['blackglass_shard'], max_active=3, respawn_minutes=12)
    area.gathering_pool('hide', ['ld_jackal_track_sand', 'bn_looters_edge_scratch'], ['reefcrawler_shell'], max_active=3, respawn_minutes=12)
    area.gathering_pool('wood', ['ld_salt_split_beam', 'cw_fallen_beam_office'], ['saltpalm_wood'], max_active=3, respawn_minutes=12)

    return area.build()
