"""Kiai Grounds -- Hub 5 exterior zone

An old ceremonial landscape of waiting rings, care basins, witness roads, and high perches. It supports preparation and reverence without turning dragon bonds into an immediate mechanical reward."""

from world.area_builder import AreaBuilder


def build():
    area = AreaBuilder('kiai_grounds')

    area.zone(
        name='Kiai Grounds',
        zone_type='frontier',
        continent='veluana',
        tier=5,
        region='veluana_archipelago',
        hub_city='korahei',
        faction_territory='kauroran',
        faction_presence=['kauroran', 'wardens'],
        world_x=72,
        world_y=2,
        world_radius=135,
    )

    area.material('reef_silverjack', tier=1, terrain='water', absorbed_property='finesse', profession_bonus={'cooking': 0.1, 'fishing': 0.05})
    area.material('saltfruit', tier=1, terrain='coastal', absorbed_property='endurance', profession_bonus={'cooking': 0.1})
    area.material('shellbean', tier=1, terrain='coastal', absorbed_property='stability', profession_bonus={'cooking': 0.1})
    area.material('kiai_blossom', tier=2, terrain='ring', absorbed_property='patience', profession_bonus={'alchemy': 0.1, 'scholarship': 0.05})
    area.material('sunleaf', tier=1, terrain='garden', absorbed_property='clarity', profession_bonus={'alchemy': 0.1})
    area.material('old_ring_basalt', tier=2, terrain='ring', absorbed_property='resonance', profession_bonus={'smithing': 0.1, 'scholarship': 0.05})
    area.material('braided_scale_shed', tier=2, terrain='ring', absorbed_property='memory', profession_bonus={'smithing': 0.05, 'scholarship': 0.05})
    area.material('circle_bamboo', tier=2, terrain='ring', absorbed_property='balance', profession_bonus={'engineering': 0.1})

    # Rooms
    wr_witness_gate = area.room('wr_witness_gate', name='Witness Gate', desc="The witness gate narrows the road until Korahei's market noise falls behind grass and ring-stone. No sign promises a dragon; the first demand is simpler and harder, arrive quietly enough to notice others.", room_type='path')
    wr_lower_witness_road = area.room('wr_lower_witness_road', name='Lower Witness Road', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on lower witness road, where small signs ask guests to lower their voices. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_grass_quiet_bend = area.room('wr_grass_quiet_bend', name='Grass-Quiet Bend', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on grass-quiet bend, where witness cords flutter from carved posts. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_corded_guest_post = area.room('wr_corded_guest_post', name='Corded Guest Post', desc="The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on corded guest post, where stone dust marks the path's old repair seams. The zone begins by slowing the player down; the first lesson is attention.", room_type='path')
    wr_stone_dust_seam = area.room('wr_stone_dust_seam', name='Stone Dust Seam', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on stone dust seam, where the city noise fades behind warm wind. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_barefoot_turn = area.room('wr_barefoot_turn', name='Barefoot Turn', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on barefoot turn, where grass has been brushed flat by careful processions. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_low_voice_marker = area.room('wr_low_voice_marker', name='Low Voice Marker', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on low voice marker, where small signs ask guests to lower their voices. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_procession_shade = area.room('wr_procession_shade', name='Procession Shade', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on procession shade, where witness cords flutter from carved posts. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_old_repair_stone = area.room('wr_old_repair_stone', name='Old Repair Stone', desc="The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on old repair stone, where stone dust marks the path's old repair seams. The zone begins by slowing the player down; the first lesson is attention.", room_type='path')
    wr_wind_lowered_step = area.room('wr_wind_lowered_step', name='Wind-Lowered Step', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on wind-lowered step, where the city noise fades behind warm wind. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_silence_ring = area.room('wr_silence_ring', name='Silence Ring', desc='A ring of brushed grass holds old processional marks and empty room for people who are not ready yet. The silence here is active, a social practice rather than a missing sound.', room_type='path')
    wr_still_drum_rest = area.room('wr_still_drum_rest', name='Still Drum Rest', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on still drum rest, where small signs ask guests to lower their voices. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_soft_garland_peg = area.room('wr_soft_garland_peg', name='Soft Garland Peg', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on soft garland peg, where witness cords flutter from carved posts. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_witness_water_jar = area.room('wr_witness_water_jar', name='Witness Water Jar', desc="The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on witness water jar, where stone dust marks the path's old repair seams. The zone begins by slowing the player down; the first lesson is attention.", room_type='path')
    wr_patient_road_rise = area.room('wr_patient_road_rise', name='Patient Road Rise', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on patient road rise, where the city noise fades behind warm wind. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_braided_boundary = area.room('wr_braided_boundary', name='Braided Boundary', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on braided boundary, where grass has been brushed flat by careful processions. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_candidate_pause = area.room('wr_candidate_pause', name='Candidate Pause', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on candidate pause, where small signs ask guests to lower their voices. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_sunlit_ring_view = area.room('wr_sunlit_ring_view', name='Sunlit Ring View', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on sunlit ring view, where witness cords flutter from carved posts. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    wr_caretakers_bend = area.room('wr_caretakers_bend', name="Caretaker's Bend", desc="The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on caretaker's bend, where stone dust marks the path's old repair seams. The zone begins by slowing the player down; the first lesson is attention.", room_type='path')
    wr_upper_witness_road = area.room('wr_upper_witness_road', name='Upper Witness Road', desc='The road from Korahei narrows into quiet grass and ring-stone, where every footprint feels like it should be earned. This part of the Witness Road centers on upper witness road, where the city noise fades behind warm wind. The zone begins by slowing the player down; the first lesson is attention.', room_type='path')
    cr_care_basin = area.room('cr_care_basin', name='Care Basin', desc='Clean water, grooming stones, and herb shelves gather around the care basin in plain sight. The place grounds wonder in work, reminding players that ceremonies are kept safe by hands that scrub and sort.', room_type='clearing')
    cr_clean_water_circle = area.room('cr_clean_water_circle', name='Clean Water Circle', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on clean water circle, where kiai blossoms grow behind low protective fences. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_brush_rack_shade = area.room('cr_brush_rack_shade', name='Brush Rack Shade', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on brush rack shade, where shed scales are braided into teaching cords. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_kiai_blossom_fence = area.room('cr_kiai_blossom_fence', name='Kiai Blossom Fence', desc='Low fencing protects pale blossoms from feet, wind, and hungry moths. Caretakers welcome help here because guarding fragile plants teaches the same patience the grounds ask from candidates.', room_type='clearing')
    cr_herb_sorting_mat = area.room('cr_herb_sorting_mat', name='Herb Sorting Mat', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on herb sorting mat, where soft brushes hang where anyone can see their use. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_scale_braid_table = area.room('cr_scale_braid_table', name='Scale Braid Table', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on scale braid table, where water bowls are cleaned until they reflect the sky. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_soft_rope_peg = area.room('cr_soft_rope_peg', name='Soft Rope Peg', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on soft rope peg, where kiai blossoms grow behind low protective fences. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_shellbean_cook_pot = area.room('cr_shellbean_cook_pot', name='Shellbean Cook Pot', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on shellbean cook pot, where shed scales are braided into teaching cords. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_warm_stone_rest = area.room('cr_warm_stone_rest', name='Warm Stone Rest', desc="Warm stones hold the day's heat near stacked towels and brushed rope. Lizards bask where tired caretakers pause, so even a rest stop asks players to share space with alert hands.", room_type='clearing')
    cr_quiet_grooming_wall = area.room('cr_quiet_grooming_wall', name='Quiet Grooming Wall', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on quiet grooming wall, where soft brushes hang where anyone can see their use. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_caregivers_ledger = area.room('cr_caregivers_ledger', name="Caregiver's Ledger", desc="Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on caregiver's ledger, where water bowls are cleaned until they reflect the sky. This subregion grounds awe in work, making the kiai feel communal rather than transactional.", room_type='clearing')
    cr_sunleaf_wash_stand = area.room('cr_sunleaf_wash_stand', name='Sunleaf Wash Stand', desc='Sunleaf bundles dry beside wash bowls and moth screens, filling the air with green salt and bruised herb. The stand draws small swarms, giving caretakers a practical reason to keep the path watched.', room_type='clearing')
    cr_long_trough_bend = area.room('cr_long_trough_bend', name='Long Trough Bend', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on long trough bend, where shed scales are braided into teaching cords. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_small_repair_hearth = area.room('cr_small_repair_hearth', name='Small Repair Hearth', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on small repair hearth, where caretakers sort herbs by smell and patience. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_dry_towel_line = area.room('cr_dry_towel_line', name='Dry Towel Line', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on dry towel line, where soft brushes hang where anyone can see their use. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_bamboo_split_bench = area.room('cr_bamboo_split_bench', name='Bamboo Split Bench', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on bamboo split bench, where water bowls are cleaned until they reflect the sky. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_fresh_water_gate = area.room('cr_fresh_water_gate', name='Fresh Water Gate', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on fresh water gate, where kiai blossoms grow behind low protective fences. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_offering_salt_jar = area.room('cr_offering_salt_jar', name='Offering Salt Jar', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on offering salt jar, where shed scales are braided into teaching cords. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_caretaker_shade = area.room('cr_caretaker_shade', name='Caretaker Shade', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on caretaker shade, where caretakers sort herbs by smell and patience. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    cr_north_care_ring = area.room('cr_north_care_ring', name='North Care Ring', desc='Care rings hold clean water, grooming stones, herb shelves, and the unglamorous labor that makes ceremony safe. This part of the Care Rings centers on north care ring, where soft brushes hang where anyone can see their use. This subregion grounds awe in work, making the kiai feel communal rather than transactional.', room_type='clearing')
    or_outer_waiting = area.room('or_outer_waiting', name='Outer Waiting', desc='Outer Waiting is deliberately plain: flat seats, water mats, and an empty center no one decorates into certainty. The room teaches that wanting a bond is not the same thing as being called.', room_type='clearing')
    or_plain_stone_seat = area.room('or_plain_stone_seat', name='Plain Stone Seat', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on plain stone seat, where old chalk marks have been washed almost clean. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_washed_chalk_ring = area.room('or_washed_chalk_ring', name='Washed Chalk Ring', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on washed chalk ring, where families leave water and food without hovering. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_family_water_mat = area.room('or_family_water_mat', name='Family Water Mat', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on family water mat, where empty space is preserved as carefully as ornament. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_empty_center_circle = area.room('or_empty_center_circle', name='Empty Center Circle', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on empty center circle, where distant animal calls rise and fall beyond the grass. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_low_patience_wall = area.room('or_low_patience_wall', name='Low Patience Wall', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on low patience wall, where flat stones face inward with no favored seat. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_sun_warmed_seat = area.room('or_sun_warmed_seat', name='Sun-Warmed Seat', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on sun-warmed seat, where old chalk marks have been washed almost clean. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_no_promise_stone = area.room('or_no_promise_stone', name='No-Promise Stone', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on no-promise stone, where families leave water and food without hovering. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_waiting_shade = area.room('or_waiting_shade', name='Waiting Shade', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on waiting shade, where empty space is preserved as carefully as ornament. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_quiet_family_rail = area.room('or_quiet_family_rail', name='Quiet Family Rail', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on quiet family rail, where distant animal calls rise and fall beyond the grass. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_uncarved_marker = area.room('or_uncarved_marker', name='Uncarved Marker', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on uncarved marker, where flat stones face inward with no favored seat. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_small_food_shelf = area.room('or_small_food_shelf', name='Small Food Shelf', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on small food shelf, where old chalk marks have been washed almost clean. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_old_witness_seat = area.room('or_old_witness_seat', name='Old Witness Seat', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on old witness seat, where families leave water and food without hovering. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_distant_call_turn = area.room('or_distant_call_turn', name='Distant Call Turn', desc='Distant animal calls rise beyond the grass at this turn, close enough to stir hope and too far to answer. Lizards cross the waiting path here, making patience practical as well as symbolic.', room_type='clearing')
    or_ring_of_no_hurry = area.room('or_ring_of_no_hurry', name='Ring of No Hurry', desc='The no-hurry ring keeps its center empty even when the road is busy. Reptile tracks cut through the dust at the edge, a small reminder that the world does not speed up for desire.', room_type='clearing')
    or_second_waiting_circle = area.room('or_second_waiting_circle', name='Second Waiting Circle', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on second waiting circle, where flat stones face inward with no favored seat. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_grass_gap_bench = area.room('or_grass_gap_bench', name='Grass Gap Bench', desc='A bench sits beside a gap in the waiting grass where moths drift from blossom fences toward shade. Families leave food nearby, and players can defend the quiet without making a performance of it.', room_type='clearing')
    or_open_sky_seat = area.room('or_open_sky_seat', name='Open Sky Seat', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on open sky seat, where families leave water and food without hovering. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_silent_handrail = area.room('or_silent_handrail', name='Silent Handrail', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on silent handrail, where empty space is preserved as carefully as ornament. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    or_waiting_road_end = area.room('or_waiting_road_end', name='Waiting Road End', desc='Outer waiting rings are deliberately plain, giving candidates, witnesses, and guests a place to sit with not knowing. This part of the Outer Waiting centers on waiting road end, where distant animal calls rise and fall beyond the grass. The drama here is restraint: no instant invitation, no menu, no promise that wanting is enough.', room_type='clearing')
    pr_preparation_ridge_mouth = area.room('pr_preparation_ridge_mouth', name='Preparation Ridge Mouth', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on preparation ridge mouth, where balance stones wobble enough to punish haste. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_balance_stone_run = area.room('pr_balance_stone_run', name='Balance Stone Run', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on balance stone run, where old shelters are stocked with simple wraps and water. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_keeper_knot_post = area.room('pr_keeper_knot_post', name='Keeper Knot Post', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on keeper knot post, where circle bamboo creaks along the ridge. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_bamboo_creak_path = area.room('pr_bamboo_creak_path', name='Bamboo Creak Path', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on bamboo creak path, where the path doubles back to make walkers notice breath. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_practice_step_loop = area.room('pr_practice_step_loop', name='Practice Step Loop', desc='Balance stones and doubled-back steps make this loop a rehearsal for humility rather than a contest. Basalt tortoises graze near the warm edge, turning footwork practice into careful coexistence.', room_type='path')
    pr_simple_wrap_shelter = area.room('pr_simple_wrap_shelter', name='Simple Wrap Shelter', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on simple wrap shelter, where balance stones wobble enough to punish haste. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_breath_turning_bend = area.room('pr_breath_turning_bend', name='Breath-Turning Bend', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on breath-turning bend, where old shelters are stocked with simple wraps and water. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_low_ridge_rest = area.room('pr_low_ridge_rest', name='Low Ridge Rest', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on low ridge rest, where circle bamboo creaks along the ridge. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_sun_peeled_marker = area.room('pr_sun_peeled_marker', name='Sun-Peeled Marker', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on sun-peeled marker, where the path doubles back to make walkers notice breath. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_footwork_dust_ring = area.room('pr_footwork_dust_ring', name='Footwork Dust Ring', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on footwork dust ring, where keeper knots mark which trail is open today. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_quiet_correction_mat = area.room('pr_quiet_correction_mat', name='Quiet Correction Mat', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on quiet correction mat, where balance stones wobble enough to punish haste. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_water_wrap_niche = area.room('pr_water_wrap_niche', name='Water Wrap Niche', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on water wrap niche, where old shelters are stocked with simple wraps and water. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_slow_return_path = area.room('pr_slow_return_path', name='Slow Return Path', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on slow return path, where circle bamboo creaks along the ridge. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_paired_step_stones = area.room('pr_paired_step_stones', name='Paired Step Stones', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on paired step stones, where the path doubles back to make walkers notice breath. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_candidate_breath_wall = area.room('pr_candidate_breath_wall', name='Candidate Breath Wall', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on candidate breath wall, where keeper knots mark which trail is open today. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_open_ridge_shelf = area.room('pr_open_ridge_shelf', name='Open Ridge Shelf', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on open ridge shelf, where balance stones wobble enough to punish haste. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_knot_checked_trail = area.room('pr_knot_checked_trail', name='Knot-Checked Trail', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on knot-checked trail, where old shelters are stocked with simple wraps and water. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_warm_palm_shade = area.room('pr_warm_palm_shade', name='Warm Palm Shade', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on warm palm shade, where circle bamboo creaks along the ridge. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    pr_old_practice_scar = area.room('pr_old_practice_scar', name='Old Practice Scar', desc='Old practice scars cross the ridge where candidates once learned to recover from bad footing. Tortoises return to the warmed marks, so every loop asks for control around stubborn living obstacles.', room_type='path')
    pr_upper_preparation_ridge = area.room('pr_upper_preparation_ridge', name='Upper Preparation Ridge', desc='Low ridges hold practice paths, balance stones, and keeper shelters where confidence is tested without spectacle. This part of the Preparation Ridges centers on upper preparation ridge, where keeper knots mark which trail is open today. Players learn that skill and humility both matter before anyone approaches the inner grounds.', room_type='path')
    hr_high_perch = area.room('hr_high_perch', name='High Perch', desc='The high perch watches the rings without intruding on them, built from quiet rails, muffled bells, and weather jars. Awe still needs lookout work, and this height makes that labor visible.', room_type='path')
    hr_muffled_bell_rail = area.room('hr_muffled_bell_rail', name='Muffled Bell Rail', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on muffled bell rail, where wind carries salt, grass, and the smell of warm stone. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_weather_watch_seat = area.room('hr_weather_watch_seat', name='Weather Watch Seat', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on weather watch seat, where perch bells stay muffled until danger calls. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_grasswind_overlook = area.room('hr_grasswind_overlook', name='Grasswind Overlook', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on grasswind overlook, where distant rings look small enough to understand as a whole. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_crowd_safety_post = area.room('hr_crowd_safety_post', name='Crowd Safety Post', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on crowd safety post, where cloud shadows move faster than the people below. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_cloud_shadow_step = area.room('hr_cloud_shadow_step', name='Cloud Shadow Step', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on cloud shadow step, where lookout rails are polished by careful hands. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_warm_stone_perch = area.room('hr_warm_stone_perch', name='Warm Stone Perch', desc='Warm stone under the perch draws moths, lizards, and watchers who know small movement can become a crowd problem. The view is beautiful because someone keeps it safe.', room_type='path')
    hr_long_ring_view = area.room('hr_long_ring_view', name='Long Ring View', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on long ring view, where perch bells stay muffled until danger calls. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_salt_wind_ledge = area.room('hr_salt_wind_ledge', name='Salt-Wind Ledge', desc='Salt wind scours the ledge and carries grass scent up from the rings below. Lizards bask along the rail braces, making the perch a place of practical caution instead of scenic emptiness.', room_type='path')
    hr_keepers_high_niche = area.room('hr_keepers_high_niche', name="Keeper's High Niche", desc="High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on keeper's high niche, where cloud shadows move faster than the people below. The heights keep the ceremony practical: awe still needs lookout work.", room_type='path')
    hr_perch_water_jar = area.room('hr_perch_water_jar', name='Perch Water Jar', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on perch water jar, where lookout rails are polished by careful hands. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_old_signal_knot = area.room('hr_old_signal_knot', name='Old Signal Knot', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on old signal knot, where wind carries salt, grass, and the smell of warm stone. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_far_city_glimpse = area.room('hr_far_city_glimpse', name='Far City Glimpse', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on far city glimpse, where perch bells stay muffled until danger calls. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_lower_roost_shelf = area.room('hr_lower_roost_shelf', name='Lower Roost Shelf', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on lower roost shelf, where distant rings look small enough to understand as a whole. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_high_bamboo_brace = area.room('hr_high_bamboo_brace', name='High Bamboo Brace', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on high bamboo brace, where cloud shadows move faster than the people below. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_rain_watch_turn = area.room('hr_rain_watch_turn', name='Rain-Watch Turn', desc='A turn in the high rail faces the weather line where sudden rain can change crowd safety in minutes. Moth swarms gather before damp air, giving watchers a living barometer and a combat nuisance.', room_type='path')
    hr_wide_ceremony_view = area.room('hr_wide_ceremony_view', name='Wide Ceremony View', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on wide ceremony view, where wind carries salt, grass, and the smell of warm stone. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_silent_bell_hook = area.room('hr_silent_bell_hook', name='Silent Bell Hook', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on silent bell hook, where perch bells stay muffled until danger calls. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_upper_roost_rail = area.room('hr_upper_roost_rail', name='Upper Roost Rail', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on upper roost rail, where distant rings look small enough to understand as a whole. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')
    hr_last_perch_stone = area.room('hr_last_perch_stone', name='Last Perch Stone', desc='High perches overlook the rings from a respectful distance, built for watching weather, animal movement, and crowd safety. This part of the High Roost Perches centers on last perch stone, where cloud shadows move faster than the people below. The heights keep the ceremony practical: awe still needs lookout work.', room_type='path')

    # Local exits
    area.exit(wr_witness_gate, wr_lower_witness_road, 'east')
    area.exit(wr_lower_witness_road, wr_witness_gate, 'west')
    area.exit(wr_lower_witness_road, wr_grass_quiet_bend, 'east')
    area.exit(wr_grass_quiet_bend, wr_lower_witness_road, 'west')
    area.exit(wr_grass_quiet_bend, wr_corded_guest_post, 'east')
    area.exit(wr_corded_guest_post, wr_grass_quiet_bend, 'west')
    area.exit(wr_corded_guest_post, wr_stone_dust_seam, 'east')
    area.exit(wr_stone_dust_seam, wr_corded_guest_post, 'west')
    area.exit(wr_stone_dust_seam, wr_barefoot_turn, 'east')
    area.exit(wr_barefoot_turn, wr_stone_dust_seam, 'west')
    area.exit(wr_barefoot_turn, wr_low_voice_marker, 'east')
    area.exit(wr_low_voice_marker, wr_barefoot_turn, 'west')
    area.exit(wr_low_voice_marker, wr_procession_shade, 'east')
    area.exit(wr_procession_shade, wr_low_voice_marker, 'west')
    area.exit(wr_procession_shade, wr_old_repair_stone, 'east')
    area.exit(wr_old_repair_stone, wr_procession_shade, 'west')
    area.exit(wr_old_repair_stone, wr_wind_lowered_step, 'east')
    area.exit(wr_wind_lowered_step, wr_old_repair_stone, 'west')
    area.exit(wr_wind_lowered_step, wr_silence_ring, 'east')
    area.exit(wr_silence_ring, wr_wind_lowered_step, 'west')
    area.exit(wr_silence_ring, wr_still_drum_rest, 'east')
    area.exit(wr_still_drum_rest, wr_silence_ring, 'west')
    area.exit(wr_still_drum_rest, wr_soft_garland_peg, 'east')
    area.exit(wr_soft_garland_peg, wr_still_drum_rest, 'west')
    area.exit(wr_soft_garland_peg, wr_witness_water_jar, 'east')
    area.exit(wr_witness_water_jar, wr_soft_garland_peg, 'west')
    area.exit(wr_witness_water_jar, wr_patient_road_rise, 'east')
    area.exit(wr_patient_road_rise, wr_witness_water_jar, 'west')
    area.exit(wr_patient_road_rise, wr_braided_boundary, 'east')
    area.exit(wr_braided_boundary, wr_patient_road_rise, 'west')
    area.exit(wr_braided_boundary, wr_candidate_pause, 'east')
    area.exit(wr_candidate_pause, wr_braided_boundary, 'west')
    area.exit(wr_candidate_pause, wr_sunlit_ring_view, 'east')
    area.exit(wr_sunlit_ring_view, wr_candidate_pause, 'west')
    area.exit(wr_sunlit_ring_view, wr_caretakers_bend, 'east')
    area.exit(wr_caretakers_bend, wr_sunlit_ring_view, 'west')
    area.exit(wr_caretakers_bend, wr_upper_witness_road, 'east')
    area.exit(wr_upper_witness_road, wr_caretakers_bend, 'west')
    area.exit(cr_care_basin, cr_clean_water_circle, 'east')
    area.exit(cr_clean_water_circle, cr_care_basin, 'west')
    area.exit(cr_clean_water_circle, cr_brush_rack_shade, 'east')
    area.exit(cr_brush_rack_shade, cr_clean_water_circle, 'west')
    area.exit(cr_brush_rack_shade, cr_kiai_blossom_fence, 'east')
    area.exit(cr_kiai_blossom_fence, cr_brush_rack_shade, 'west')
    area.exit(cr_kiai_blossom_fence, cr_herb_sorting_mat, 'east')
    area.exit(cr_herb_sorting_mat, cr_kiai_blossom_fence, 'west')
    area.exit(cr_herb_sorting_mat, cr_scale_braid_table, 'east')
    area.exit(cr_scale_braid_table, cr_herb_sorting_mat, 'west')
    area.exit(cr_scale_braid_table, cr_soft_rope_peg, 'east')
    area.exit(cr_soft_rope_peg, cr_scale_braid_table, 'west')
    area.exit(cr_soft_rope_peg, cr_shellbean_cook_pot, 'east')
    area.exit(cr_shellbean_cook_pot, cr_soft_rope_peg, 'west')
    area.exit(cr_shellbean_cook_pot, cr_warm_stone_rest, 'east')
    area.exit(cr_warm_stone_rest, cr_shellbean_cook_pot, 'west')
    area.exit(cr_warm_stone_rest, cr_quiet_grooming_wall, 'east')
    area.exit(cr_quiet_grooming_wall, cr_warm_stone_rest, 'west')
    area.exit(cr_quiet_grooming_wall, cr_caregivers_ledger, 'east')
    area.exit(cr_caregivers_ledger, cr_quiet_grooming_wall, 'west')
    area.exit(cr_caregivers_ledger, cr_sunleaf_wash_stand, 'east')
    area.exit(cr_sunleaf_wash_stand, cr_caregivers_ledger, 'west')
    area.exit(cr_sunleaf_wash_stand, cr_long_trough_bend, 'east')
    area.exit(cr_long_trough_bend, cr_sunleaf_wash_stand, 'west')
    area.exit(cr_long_trough_bend, cr_small_repair_hearth, 'east')
    area.exit(cr_small_repair_hearth, cr_long_trough_bend, 'west')
    area.exit(cr_small_repair_hearth, cr_dry_towel_line, 'east')
    area.exit(cr_dry_towel_line, cr_small_repair_hearth, 'west')
    area.exit(cr_dry_towel_line, cr_bamboo_split_bench, 'east')
    area.exit(cr_bamboo_split_bench, cr_dry_towel_line, 'west')
    area.exit(cr_bamboo_split_bench, cr_fresh_water_gate, 'east')
    area.exit(cr_fresh_water_gate, cr_bamboo_split_bench, 'west')
    area.exit(cr_fresh_water_gate, cr_offering_salt_jar, 'east')
    area.exit(cr_offering_salt_jar, cr_fresh_water_gate, 'west')
    area.exit(cr_offering_salt_jar, cr_caretaker_shade, 'east')
    area.exit(cr_caretaker_shade, cr_offering_salt_jar, 'west')
    area.exit(cr_caretaker_shade, cr_north_care_ring, 'east')
    area.exit(cr_north_care_ring, cr_caretaker_shade, 'west')
    area.exit(or_outer_waiting, or_plain_stone_seat, 'east')
    area.exit(or_plain_stone_seat, or_outer_waiting, 'west')
    area.exit(or_plain_stone_seat, or_washed_chalk_ring, 'east')
    area.exit(or_washed_chalk_ring, or_plain_stone_seat, 'west')
    area.exit(or_washed_chalk_ring, or_family_water_mat, 'east')
    area.exit(or_family_water_mat, or_washed_chalk_ring, 'west')
    area.exit(or_family_water_mat, or_empty_center_circle, 'east')
    area.exit(or_empty_center_circle, or_family_water_mat, 'west')
    area.exit(or_empty_center_circle, or_low_patience_wall, 'east')
    area.exit(or_low_patience_wall, or_empty_center_circle, 'west')
    area.exit(or_low_patience_wall, or_sun_warmed_seat, 'east')
    area.exit(or_sun_warmed_seat, or_low_patience_wall, 'west')
    area.exit(or_sun_warmed_seat, or_no_promise_stone, 'east')
    area.exit(or_no_promise_stone, or_sun_warmed_seat, 'west')
    area.exit(or_no_promise_stone, or_waiting_shade, 'east')
    area.exit(or_waiting_shade, or_no_promise_stone, 'west')
    area.exit(or_waiting_shade, or_quiet_family_rail, 'east')
    area.exit(or_quiet_family_rail, or_waiting_shade, 'west')
    area.exit(or_quiet_family_rail, or_uncarved_marker, 'east')
    area.exit(or_uncarved_marker, or_quiet_family_rail, 'west')
    area.exit(or_uncarved_marker, or_small_food_shelf, 'east')
    area.exit(or_small_food_shelf, or_uncarved_marker, 'west')
    area.exit(or_small_food_shelf, or_old_witness_seat, 'east')
    area.exit(or_old_witness_seat, or_small_food_shelf, 'west')
    area.exit(or_old_witness_seat, or_distant_call_turn, 'east')
    area.exit(or_distant_call_turn, or_old_witness_seat, 'west')
    area.exit(or_distant_call_turn, or_ring_of_no_hurry, 'east')
    area.exit(or_ring_of_no_hurry, or_distant_call_turn, 'west')
    area.exit(or_ring_of_no_hurry, or_second_waiting_circle, 'east')
    area.exit(or_second_waiting_circle, or_ring_of_no_hurry, 'west')
    area.exit(or_second_waiting_circle, or_grass_gap_bench, 'east')
    area.exit(or_grass_gap_bench, or_second_waiting_circle, 'west')
    area.exit(or_grass_gap_bench, or_open_sky_seat, 'east')
    area.exit(or_open_sky_seat, or_grass_gap_bench, 'west')
    area.exit(or_open_sky_seat, or_silent_handrail, 'east')
    area.exit(or_silent_handrail, or_open_sky_seat, 'west')
    area.exit(or_silent_handrail, or_waiting_road_end, 'east')
    area.exit(or_waiting_road_end, or_silent_handrail, 'west')
    area.exit(pr_preparation_ridge_mouth, pr_balance_stone_run, 'east')
    area.exit(pr_balance_stone_run, pr_preparation_ridge_mouth, 'west')
    area.exit(pr_balance_stone_run, pr_keeper_knot_post, 'east')
    area.exit(pr_keeper_knot_post, pr_balance_stone_run, 'west')
    area.exit(pr_keeper_knot_post, pr_bamboo_creak_path, 'east')
    area.exit(pr_bamboo_creak_path, pr_keeper_knot_post, 'west')
    area.exit(pr_bamboo_creak_path, pr_practice_step_loop, 'east')
    area.exit(pr_practice_step_loop, pr_bamboo_creak_path, 'west')
    area.exit(pr_practice_step_loop, pr_simple_wrap_shelter, 'east')
    area.exit(pr_simple_wrap_shelter, pr_practice_step_loop, 'west')
    area.exit(pr_simple_wrap_shelter, pr_breath_turning_bend, 'east')
    area.exit(pr_breath_turning_bend, pr_simple_wrap_shelter, 'west')
    area.exit(pr_breath_turning_bend, pr_low_ridge_rest, 'east')
    area.exit(pr_low_ridge_rest, pr_breath_turning_bend, 'west')
    area.exit(pr_low_ridge_rest, pr_sun_peeled_marker, 'east')
    area.exit(pr_sun_peeled_marker, pr_low_ridge_rest, 'west')
    area.exit(pr_sun_peeled_marker, pr_footwork_dust_ring, 'east')
    area.exit(pr_footwork_dust_ring, pr_sun_peeled_marker, 'west')
    area.exit(pr_footwork_dust_ring, pr_quiet_correction_mat, 'east')
    area.exit(pr_quiet_correction_mat, pr_footwork_dust_ring, 'west')
    area.exit(pr_quiet_correction_mat, pr_water_wrap_niche, 'east')
    area.exit(pr_water_wrap_niche, pr_quiet_correction_mat, 'west')
    area.exit(pr_water_wrap_niche, pr_slow_return_path, 'east')
    area.exit(pr_slow_return_path, pr_water_wrap_niche, 'west')
    area.exit(pr_slow_return_path, pr_paired_step_stones, 'east')
    area.exit(pr_paired_step_stones, pr_slow_return_path, 'west')
    area.exit(pr_paired_step_stones, pr_candidate_breath_wall, 'east')
    area.exit(pr_candidate_breath_wall, pr_paired_step_stones, 'west')
    area.exit(pr_candidate_breath_wall, pr_open_ridge_shelf, 'east')
    area.exit(pr_open_ridge_shelf, pr_candidate_breath_wall, 'west')
    area.exit(pr_open_ridge_shelf, pr_knot_checked_trail, 'east')
    area.exit(pr_knot_checked_trail, pr_open_ridge_shelf, 'west')
    area.exit(pr_knot_checked_trail, pr_warm_palm_shade, 'east')
    area.exit(pr_warm_palm_shade, pr_knot_checked_trail, 'west')
    area.exit(pr_warm_palm_shade, pr_old_practice_scar, 'east')
    area.exit(pr_old_practice_scar, pr_warm_palm_shade, 'west')
    area.exit(pr_old_practice_scar, pr_upper_preparation_ridge, 'east')
    area.exit(pr_upper_preparation_ridge, pr_old_practice_scar, 'west')
    area.exit(hr_high_perch, hr_muffled_bell_rail, 'east')
    area.exit(hr_muffled_bell_rail, hr_high_perch, 'west')
    area.exit(hr_muffled_bell_rail, hr_weather_watch_seat, 'east')
    area.exit(hr_weather_watch_seat, hr_muffled_bell_rail, 'west')
    area.exit(hr_weather_watch_seat, hr_grasswind_overlook, 'east')
    area.exit(hr_grasswind_overlook, hr_weather_watch_seat, 'west')
    area.exit(hr_grasswind_overlook, hr_crowd_safety_post, 'east')
    area.exit(hr_crowd_safety_post, hr_grasswind_overlook, 'west')
    area.exit(hr_crowd_safety_post, hr_cloud_shadow_step, 'east')
    area.exit(hr_cloud_shadow_step, hr_crowd_safety_post, 'west')
    area.exit(hr_cloud_shadow_step, hr_warm_stone_perch, 'east')
    area.exit(hr_warm_stone_perch, hr_cloud_shadow_step, 'west')
    area.exit(hr_warm_stone_perch, hr_long_ring_view, 'east')
    area.exit(hr_long_ring_view, hr_warm_stone_perch, 'west')
    area.exit(hr_long_ring_view, hr_salt_wind_ledge, 'east')
    area.exit(hr_salt_wind_ledge, hr_long_ring_view, 'west')
    area.exit(hr_salt_wind_ledge, hr_keepers_high_niche, 'east')
    area.exit(hr_keepers_high_niche, hr_salt_wind_ledge, 'west')
    area.exit(hr_keepers_high_niche, hr_perch_water_jar, 'east')
    area.exit(hr_perch_water_jar, hr_keepers_high_niche, 'west')
    area.exit(hr_perch_water_jar, hr_old_signal_knot, 'east')
    area.exit(hr_old_signal_knot, hr_perch_water_jar, 'west')
    area.exit(hr_old_signal_knot, hr_far_city_glimpse, 'east')
    area.exit(hr_far_city_glimpse, hr_old_signal_knot, 'west')
    area.exit(hr_far_city_glimpse, hr_lower_roost_shelf, 'east')
    area.exit(hr_lower_roost_shelf, hr_far_city_glimpse, 'west')
    area.exit(hr_lower_roost_shelf, hr_high_bamboo_brace, 'east')
    area.exit(hr_high_bamboo_brace, hr_lower_roost_shelf, 'west')
    area.exit(hr_high_bamboo_brace, hr_rain_watch_turn, 'east')
    area.exit(hr_rain_watch_turn, hr_high_bamboo_brace, 'west')
    area.exit(hr_rain_watch_turn, hr_wide_ceremony_view, 'east')
    area.exit(hr_wide_ceremony_view, hr_rain_watch_turn, 'west')
    area.exit(hr_wide_ceremony_view, hr_silent_bell_hook, 'east')
    area.exit(hr_silent_bell_hook, hr_wide_ceremony_view, 'west')
    area.exit(hr_silent_bell_hook, hr_upper_roost_rail, 'east')
    area.exit(hr_upper_roost_rail, hr_silent_bell_hook, 'west')
    area.exit(hr_upper_roost_rail, hr_last_perch_stone, 'east')
    area.exit(hr_last_perch_stone, hr_upper_roost_rail, 'west')
    area.exit(wr_upper_witness_road, cr_care_basin, 'north')
    area.exit(cr_care_basin, wr_upper_witness_road, 'south')
    area.exit(cr_north_care_ring, or_outer_waiting, 'north')
    area.exit(or_outer_waiting, cr_north_care_ring, 'south')
    area.exit(or_waiting_road_end, pr_preparation_ridge_mouth, 'north')
    area.exit(pr_preparation_ridge_mouth, or_waiting_road_end, 'south')
    area.exit(pr_upper_preparation_ridge, hr_high_perch, 'north')
    area.exit(hr_high_perch, pr_upper_preparation_ridge, 'south')
    area.exit(wr_witness_gate, 'korahei:kg_kiai_gate', 'south')

    # NPCs
    _caretaker = area.npc(cr_care_basin, 'npc_kiai_caretaker_maluhia', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Caretaker Maluhia studies you with open attention.'}, 'topics': {'help': 'Keeps the care rings practical and the ritual from becoming a spectacle.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Caretaker Maluhia adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})
    _witness_lio = area.npc(wr_silence_ring, 'npc_circle_witness_lio', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Witness Lio studies you with open attention.'}, 'topics': {'help': 'Teaches silence, posture, and the discipline of not forcing meaning.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Witness Lio adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})
    _keeper_sene = area.npc(hr_high_perch, 'npc_perch_keeper_sene', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Perch Keeper Sene studies you with open attention.'}, 'topics': {'help': 'Watches weather and crowd safety from above the rings.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Perch Keeper Sene adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})

    # Quest and delivery item templates
    area.item('kiai_patient_steps_record', key='patient-steps record', item_type='item', weight=0.1, rarity='normal', desc='A simple record of where you waited, helped, and listened.', value=0, is_quest_item=True)
    area.quest(
        'kiai_q_witness_silence',
        name='Witness Silence',
        description='Maluhia asks you to learn the witness road before asking anything of the grounds, keeping the kiai patient and earned.',
        quest_type='exploration',
        quest_giver='npc_kiai_caretaker_maluhia',
        objectives=[{'type': 'investigate', 'target': 'wr_silence_ring', 'count': 1}, {'type': 'investigate', 'target': 'or_outer_waiting', 'count': 1}, {'type': 'talk_to', 'target': 'npc_circle_witness_lio', 'count': 1}],
        rewards=[{'action_type': 'give_scales', 'amount': 28}, {'action_type': 'modify_standing', 'faction_id': 'kauroran', 'delta': 3500}, {'action_type': 'modify_attunement', 'zone_id': 'kiai_grounds', 'delta': 12, 'effect_id': 'kiai_q_witness_silence:attunement', 'message': '|cThe waiting road settles into your sense of the grounds.|n'}],
        next_quest_id='kiai_q_clean_bowls',
        prerequisite_quests=['kor_q_warden_guest'],
        can_share=True,
        consequence_small='Maluhia ties a quiet witness cord at the road edge, noting that you learned to arrive before asking to be seen.',
    )
    area.quest(
        'kiai_q_clean_bowls',
        name='Clean Bowls, Clear Hands',
        description='Lio turns preparation into a gathering lesson: blossoms, bamboo, and clean water matter before any ceremony does.',
        quest_type='gathering',
        quest_giver='npc_circle_witness_lio',
        objectives=[{'type': 'collect', 'target': 'kiai_blossom', 'count': 2}, {'type': 'collect', 'target': 'circle_bamboo', 'count': 2}, {'type': 'investigate', 'target': 'cr_care_basin', 'count': 1}],
        rewards=[{'action_type': 'give_scales', 'amount': 30}, {'action_type': 'give_skill_xp', 'skill_id': 'herbalism', 'count': 10}],
        next_quest_id='kiai_q_patient_steps',
        prerequisite_quests=['kiai_q_witness_silence'],
        can_share=True,
        consequence_small='Lio places your cleaned bowl among the ready set, proof that preparation can leave the next guest safer.',
    )
    area.quest(
        'kiai_q_patient_steps',
        name='Patient Steps',
        description='Sene sends a record of patient work toward the central isle pathfinder, linking kiai preparation to wider island stewardship.',
        quest_type='delivery',
        quest_giver='npc_perch_keeper_sene',
        objectives=[{'type': 'investigate', 'target': 'hr_high_perch', 'count': 1}, {'type': 'deliver', 'target': 'npc_central_pathfinder_inoa', 'count': 1, 'item_tag': 'kiai_patient_steps_record'}],
        rewards=[{'action_type': 'give_scales', 'amount': 32}, {'action_type': 'give_skill_xp', 'skill_id': 'scholarship', 'count': 8}],
        next_quest_id='central_q_loop_walk',
        prerequisite_quests=['kiai_q_clean_bowls'],
        can_share=True,
        consequence_small='Sene seals your patient-steps record with a perch knot, giving Inoa a route note earned by waiting and work.',
    )

    # Spawns
    area.spawn(cr_kiai_blossom_fence, 'ring_moth_swarm', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(cr_sunleaf_wash_stand, 'ring_moth_swarm', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(cr_warm_stone_rest, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(or_distant_call_turn, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(or_ring_of_no_hurry, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(or_grass_gap_bench, 'ring_moth_swarm', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(pr_practice_step_loop, 'basalt_tortoise', count_min=1, count_max=1, respawn_minutes=18)
    area.spawn(pr_old_practice_scar, 'basalt_tortoise', count_min=1, count_max=1, respawn_minutes=18)
    area.spawn(hr_warm_stone_perch, 'ring_moth_swarm', count_min=1, count_max=3, respawn_minutes=18)
    area.spawn(hr_rain_watch_turn, 'ring_moth_swarm', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(hr_salt_wind_ledge, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)

    # Gathering pools
    area.gathering_pool('fish', ['cr_fresh_water_gate', 'wr_witness_water_jar'], ['reef_silverjack'], max_active=3, respawn_minutes=12)
    area.gathering_pool('forage', ['cr_shellbean_cook_pot', 'or_small_food_shelf'], ['shellbean', 'saltfruit'], max_active=3, respawn_minutes=12)
    area.gathering_pool('herb', ['cr_kiai_blossom_fence', 'cr_sunleaf_wash_stand'], ['kiai_blossom', 'sunleaf'], max_active=3, respawn_minutes=12)
    area.gathering_pool('ore', ['wr_old_repair_stone', 'or_plain_stone_seat'], ['old_ring_basalt'], max_active=3, respawn_minutes=12)
    area.gathering_pool('hide', ['cr_scale_braid_table', 'pr_old_practice_scar'], ['braided_scale_shed'], max_active=3, respawn_minutes=12)
    area.gathering_pool('wood', ['pr_bamboo_creak_path', 'cr_bamboo_split_bench'], ['circle_bamboo'], max_active=3, respawn_minutes=12)

    return area.build()
