"""Velu'ana Outer Reefs -- Hub 5 exterior zone

A bright reef approach where fishing, gathering, tide reading, and community labor turn exploration into practical belonging."""

from world.area_builder import AreaBuilder


def build():
    area = AreaBuilder('veluana_outer_reefs')

    area.zone(
        name="Velu'ana Outer Reefs",
        zone_type='coastal',
        continent='veluana',
        tier=5,
        region='veluana_archipelago',
        hub_city='korahei',
        faction_territory='kauroran',
        faction_presence=['kauroran', 'raider'],
        world_x=77,
        world_y=-6,
        world_radius=130,
    )

    area.material('reef_silverjack', tier=1, terrain='water', absorbed_property='finesse', profession_bonus={'cooking': 0.1, 'fishing': 0.05})
    area.material('tide_eel', tier=2, terrain='water', absorbed_property='timing', profession_bonus={'cooking': 0.1, 'alchemy': 0.05})
    area.material('sunscale_snapper', tier=2, terrain='water', absorbed_property='vitality', profession_bonus={'cooking': 0.1, 'fishing': 0.05})
    area.material('reef_kelp', tier=1, terrain='reef', absorbed_property='flexibility', profession_bonus={'cooking': 0.05, 'alchemy': 0.05})
    area.material('tide_mint', tier=1, terrain='water', absorbed_property='cooling', profession_bonus={'alchemy': 0.1, 'cooking': 0.05})
    area.material('reefstone', tier=1, terrain='reef', absorbed_property='durability', profession_bonus={'smithing': 0.1, 'engineering': 0.05})
    area.material('reefcrawler_shell', tier=1, terrain='reef', absorbed_property='protection', profession_bonus={'smithing': 0.1})
    area.material('shore_drake_hide', tier=2, terrain='coastal', absorbed_property='resilience', profession_bonus={'smithing': 0.1})
    area.material('saltpalm_wood', tier=1, terrain='coastal', absorbed_property='flexibility', profession_bonus={'engineering': 0.1})

    # Rooms
    rl_korahei_landing = area.room('rl_korahei_landing', name='Korahei Landing', desc='Low shelves step down from Korahei into reef glare, each stone scored by canoe keels and warning cord. The landing makes the first lesson plain: the route is open, but the tide gets a vote.', room_type='path')
    rl_landing_pole_shelf = area.room('rl_landing_pole_shelf', name='Landing Pole Shelf', desc='Weather-grey landing poles rise from a shelf scuffed by canoe prows. Fresh rope darkens the stone between two moorings, and every knot has been set above the next high-water stain.', room_type='path')
    rl_rope_wet_step = area.room('rl_rope_wet_step', name='Rope-Wet Step', desc='A broad step stays wet even while the surrounding reef dries to white glare. Haulers have braided a handline through holes in the rock, its fibers swollen with salt and the pull of loaded baskets.', room_type='path')
    rl_canoe_scar_stone = area.room('rl_canoe_scar_stone', name='Canoe Scar Stone', desc='Generations of hulls have polished a curved groove through the coralstone. Wood shavings and a dab of fresh sealing pitch show that a fishing crew repaired its canoe here this morning.', room_type='path')
    rl_low_coral_ramp = area.room('rl_low_coral_ramp', name='Low Coral Ramp', desc='A natural coral ramp slopes toward ankle-deep water, rough underfoot except where the tide has glazed it smooth. Bare footprints follow a pale seam upward while crab tracks wander heedlessly across it.', room_type='path')
    rl_shell_warning_cord = area.room('rl_shell_warning_cord', name='Shell Warning Cord', desc='A red cord strung with black shells crosses the route at knee height. The shells clatter when the wind turns shoreward, warning that water is already folding across the lower stones.', room_type='path')
    rl_silver_scale_crack = area.room('rl_silver_scale_crack', name='Silver Scale Crack', desc='A narrow crack catches the silver scales washed from cleaning boards above. Tiny fish nose into the glittering seam, then scatter whenever a shadow passes over the water.', room_type='path')
    rl_barefoot_marker = area.room('rl_barefoot_marker', name='Barefoot Marker', desc='Two ochre feet are painted on a flat stone where the safe route narrows. Islanders step here without looking; visitors slow down when they notice the barnacles waiting beyond the painted toes.', room_type='path')
    rl_bright_foam_lip = area.room('rl_bright_foam_lip', name='Bright Foam Lip', desc='White foam curls over a low lip and drains through a lace of coral holes. Each retreating wave leaves a brief path of bubbles pointing toward the higher shelf.', room_type='path')
    rl_kelp_dark_pocket = area.room('rl_kelp_dark_pocket', name='Kelp-Dark Pocket', desc='Kelp crowds a shaded pocket between sunlit slabs, its long blades rising and sinking with the swell. A stone weight and snapped basket handle lie below, visible only when the water draws back.', room_type='path')
    rl_tide_polished_turn = area.room('rl_tide_polished_turn', name='Tide-Polished Turn', desc='The route bends around a bulge polished smooth as old glass. Chalk arrows climb toward Korahei, but a lower set has been scrubbed almost away by the returning tide.', room_type='path')
    rl_reefbird_perch = area.room('rl_reefbird_perch', name='Reefbird Perch', desc='A salt-bleached branch has been wedged upright for reefbirds to claim. Their cries follow every opened basket, and a patient watcher can see the flock wheel away from approaching squalls.', room_type='path')
    rl_sun_slick_shelf = area.room('rl_sun_slick_shelf', name='Sun-Slick Shelf', desc='No shade reaches this broad shelf, where salt crystals flash hard enough to blur the horizon. Sand scattered over the slickest patches marks a route renewed by many careful hands.', room_type='path')
    rl_saltpalm_lean = area.room('rl_saltpalm_lean', name='Saltpalm Lean', desc='A wind-bent saltpalm leans over the reef, its roots gripping a pocket of shell grit. Someone has tucked a water gourd beneath the fronds and tied a blue thread around its neck for the next traveler.', room_type='path')
    rl_old_mooring_peg = area.room('rl_old_mooring_peg', name='Old Mooring Peg', desc='An ironwood peg survives in a socket cut for a larger harbor than the reef now needs. The newest rope scar crosses older grooves at different angles, a quiet record of changing currents.', room_type='path')
    rl_basket_rest_stone = area.room('rl_basket_rest_stone', name='Basket Rest Stone', desc='A waist-high stone offers a dry place to set a catch basket before the climb. Crushed herbs scent its rim, left by gatherers sorting useful reef plants from stinging lookalikes.', room_type='path')
    rl_fish_gut_rill = area.room('rl_fish_gut_rill', name='Fish-Gut Rill', desc='A narrow rill carries scales and fish blood away from the landing boards. Reefcrawlers gather where it meets the sea, bold from easy meals and quick to defend the richest cracks.', room_type='path')
    rl_safe_line_cairn = area.room('rl_safe_line_cairn', name='Safe-Line Cairn', desc='Flat stones stacked waist high mark the last route that remains dry through an ordinary tide. New shell chips on its eastern face point toward damage from the latest storm.', room_type='path')
    rl_outer_water_glance = area.room('rl_outer_water_glance', name='Outer Water Glance', desc='The shelves open to a first uninterrupted view of the outer water. Canoe sails move between the glare and distant rain, while darker shapes turn below the reef edge and vanish.', room_type='path')
    rl_first_tide_fork = area.room('rl_first_tide_fork', name='First Tide Fork', desc='Two reef paths divide around a pool filling from below. White pole paint marks the shoreward way; a strand of fresh green kelp points toward the flats and whatever the falling water has uncovered.', room_type='path')
    tm_tide_marker = area.room('tm_tide_marker', name='Tide Marker', desc="The first marker leans above shallow water with storm notches cut deep enough to hold shadow. Tavake has chalked the morning tide beside older cuts, leaving room for anyone who returns with a truer reading.", room_type='clearing')
    tm_first_notch_stone = area.room('tm_first_notch_stone', name='First Notch Stone', desc='One shallow groove circles this waist-high marker, the first flood height children learn to recognize. A loop of net twine holds shell beads at its base, each bead naming a boat expected home before dark.', room_type='clearing')
    tm_storm_line_marker = area.room('tm_storm_line_marker', name='Storm-Line Marker', desc='Deep cuts climb the seaward face of a basalt pillar, with dates and family marks packed between them. The highest line stands above eye level, bleached by a storm still invoked whenever the horizon turns green.', room_type='clearing')
    tm_kelp_tied_cairn = area.room('tm_kelp_tied_cairn', name='Kelp-Tied Cairn', desc='Fresh kelp binds a low cairn whose stones would otherwise roll with the wash. The knot is replaced every dawn, so its color quietly measures how long the flats have gone untended.', room_type='clearing')
    tm_fresh_seep_pool = area.room('tm_fresh_seep_pool', name='Fresh Seep Pool', desc='Cold fresh water wells through a crack into a pool rimmed with salt. Birds, gatherers, and reefcrawlers all approach from different sides, leaving a crowded map of tracks around the clear center.', room_type='clearing')
    tm_long_flat_shimmer = area.room('tm_long_flat_shimmer', name='Long Flat Shimmer', desc='Heat and salt turn the flats ahead into a wavering mirror. Marker tops remain visible through the dazzle, a patient dotted line toward ground that rises before the next tide.', room_type='clearing')
    tm_crawler_dotted_sand = area.room('tm_crawler_dotted_sand', name='Crawler Dotted Sand', desc='Dotted trails stitch the damp sand between marker stones where reefcrawlers feed on stranded weed. The flats are safe enough to learn on, but the moving shells make steady footwork matter.', room_type='clearing')
    tm_white_shell_count = area.room('tm_white_shell_count', name='White Shell Count', desc='Eight rows of white shells have been pressed into the wet sand beside the marker. Two rows are disturbed by crawler tracks, and a child has carefully begun the count again on higher ground.', room_type='clearing')
    tm_marker_of_lost_nets = area.room('tm_marker_of_lost_nets', name='Marker of Lost Nets', desc='Lengths of torn net hang from a forked post, their floats whitened by years of sun. Fishers touch the oldest knots as they pass and add new cord when the reef takes another cast.', room_type='clearing')
    tm_second_tide_bend = area.room('tm_second_tide_bend', name='Second-Tide Bend', desc='A crescent of marker stones bends inland where the second tide cuts across the direct route. Water already whispers through the outer channels, making the longer path look wiser with every minute.', room_type='clearing')
    tm_sun_dazzle_pool = area.room('tm_sun_dazzle_pool', name='Sun-Dazzle Pool', desc='A broad pool holds the sky so brightly that its depth disappears. Charcoal smudges on the nearest stone frame a safe stepping line visible even through the reflected glare.', room_type='clearing')
    tm_low_warning_stake = area.room('tm_low_warning_stake', name='Low Warning Stake', desc='Only a handspan of this warning stake remains above the sand. Its yellow binding means the next channel floods quickly, and damp fibers show someone checked it after the last turn of water.', room_type='clearing')
    tm_tide_mint_patch = area.room('tm_tide_mint_patch', name='Tide Mint Patch', desc='Blue-green tide mint flourishes where a fresh seep threads through salt crust. Harvesters pinch only the upper leaves and leave woven shade screens so the patch survives the noon glare.', room_type='clearing')
    tm_salt_mirror_run = area.room('tm_salt_mirror_run', name='Salt Mirror Run', desc='A finger-deep run of water reflects every cloud with impossible sharpness. The mirror breaks around hidden shell ridges, revealing a crooked dry line to those who watch instead of wading straight through.', room_type='clearing')
    tm_fishers_chalk_post = area.room('tm_fishers_chalk_post', name="Fisher's Chalk Post", desc='Daily notes crowd a black post: tide times, net damage, eel sightings, and three boats still outside the reef. New chalk lies beneath an oilskin flap for the next crew returning with news.', room_type='clearing')
    tm_young_marker_stone = area.room('tm_young_marker_stone', name='Young Marker Stone', desc='This marker is lighter than its weathered neighbors and still bears chisel dust in protected seams. Small handprints ring the base where island children helped set it after the old stone split.', room_type='clearing')
    tm_old_storm_scar = area.room('tm_old_storm_scar', name='Old Storm Scar', desc='A storm gouge crosses the flat from sea to reefstone, wide enough to swallow the usual footpath. Driftwood braces now span the cut, replaced so often that each rail carries a different family mark.', room_type='clearing')
    tm_grey_crab_hollow = area.room('tm_grey_crab_hollow', name='Grey Crab Hollow', desc='Grey hollows pock the flat where crawler shells vanish under a skin of sand. A patient hunter can work the pocket in a loop, but every marker nearby warns against chasing too far on a falling tide.', room_type='clearing')
    tm_raised_sand_tongue = area.room('tm_raised_sand_tongue', name='Raised Sand Tongue', desc='A raised tongue of sand holds longer than the flats around it, drawing reefcrawlers into a narrow feeding line. The place gives combat a visible reason: clear the path, then step back before water closes it.', room_type='clearing')
    tm_far_marker_rise = area.room('tm_far_marker_rise', name='Far Marker Rise', desc='The last marker stands on a hummock that remains dry while the flats begin to fill. From here, every cairn behind forms a visible path home and the kelp pockets ahead darken with deeper water.', room_type='clearing')
    kp_fishing_shelf = area.room('kp_fishing_shelf', name='Fishing Shelf', desc='The fishing shelf smells of iodine, cut kelp, and patient hands. Anglers sit above green pockets while mentors point out which ripples mean fish, which mean eel shade, and which mean a boot should move.', room_type='clearing')
    kp_green_pocket_mouth = area.room('kp_green_pocket_mouth', name='Green Pocket Mouth', desc='Two arms of reefstone shelter a green pocket where kelp rises almost to the surface. Silverjack fry crowd the warm mouth until a larger shadow sends them flashing into the weeds.', room_type='clearing')
    kp_net_stake_lane = area.room('kp_net_stake_lane', name='Net Stake Lane', desc='Ironwood stakes make a narrow lane through the kelp, each leaning with the prevailing pull. Empty loops show where fishers remove their nets between runs rather than leave the channel strangled.', room_type='clearing')
    kp_iodine_stone_seat = area.room('kp_iodine_stone_seat', name='Iodine Stone Seat', desc='A round boulder stained brown by drying weed serves as a seat above the pocket. The sharp iodine smell clings to knife grooves where harvesters trim damaged fronds and return the living holdfasts.', room_type='clearing')
    kp_deep_kelp_window = area.room('kp_deep_kelp_window', name='Deep Kelp Window', desc='A break in the canopy opens onto water far deeper than the pale reef around it. Fish drift through the blue window in slow schools, but bubbles rising from below warn that the current has another entrance.', room_type='clearing')
    kp_silverjack_flicker = area.room('kp_silverjack_flicker', name='Silverjack Flicker', desc='Silverjacks turn beneath the weed in a single bright sheet, vanishing whenever the kelp closes. A line of shell lures hangs ready above them, baited lightly enough to leave the smallest fish behind.', room_type='clearing')
    kp_half_tide_basin = area.room('kp_half_tide_basin', name='Half-Tide Basin', desc='The basin is placid at half tide, with kelp tips drawing circles on its green surface. Water stains show how quickly the calm space fills, and bundled catches have been staged well above the upper mark.', room_type='clearing')
    kp_slick_round_seat = area.room('kp_slick_round_seat', name='Slick Round Seat', desc='A dome of reefstone offers a perfect fishing seat and a treacherous layer of spray-slick algae. A woven foot loop has been anchored below the rim by someone tired of watching proud anglers slide into the basin.', room_type='clearing')
    kp_anglers_patience_rock = area.room('kp_anglers_patience_rock', name="Angler's Patience Rock", desc='Notches around this low rock record long waits rather than large catches. A covered clay cup holds cool tea beside a single line, suggesting its owner expects the fish to set the pace.', room_type='clearing')
    kp_cut_kelp_mat = area.room('kp_cut_kelp_mat', name='Cut Kelp Mat', desc="Freshly cut blades lie in a neat mat, sorted by thickness for food, cord, and medicine. The uncut edge of the bed remains dense, marked with blue ties so tomorrow's harvest begins elsewhere.", room_type='clearing')
    kp_swaying_weed_gate = area.room('kp_swaying_weed_gate', name='Swaying Weed Gate', desc='Two heavy curtains of kelp part and close across the channel with each swell. Bits of red yarn tied high on the fronds reveal which opening leads through and which folds into a submerged wall.', room_type='clearing')
    kp_hidden_foot_pool = area.room('kp_hidden_foot_pool', name='Hidden Foot Pool', desc='Kelp hides a foot-deep pool beside the repair shelf, exactly where careless workers step while dragging nets. Reefcrawlers gather in the shadow, turning net work into a small but honest hazard.', room_type='clearing')
    kp_old_hook_crack = area.room('kp_old_hook_crack', name='Old Hook Crack', desc='Bent hooks and snapped points have accumulated in a crack beyond reach of bare fingers. Recent fish scales shine beside the oldest rust, proof that the narrow channel still takes gear from anyone pulling too late.', room_type='clearing')
    kp_tide_eel_shade = area.room('kp_tide_eel_shade', name='Tide Eel Shade', desc='The weed canopy darkens into eel shade, cool enough to draw reptiles and slick enough to punish haste. Fishers mark the stones here because useful water and dangerous water are often the same place.', room_type='clearing')
    kp_pressed_kelp_slab = area.room('kp_pressed_kelp_slab', name='Pressed Kelp Slab', desc='A flat slab and three smooth weights form a communal press above the tide line. Dark juice runs through carved channels into stoppered jars while salted sheets cure beneath reed screens.', room_type='clearing')
    kp_fish_shadow_turn = area.room('kp_fish_shadow_turn', name='Fish Shadow Turn', desc='The kelp lane bends around a stone shoulder where fish shadows gather before entering open water. Their shapes scatter upward when tide eels hunt below, turning the surface into a readable warning.', room_type='clearing')
    kp_wet_basket_ledge = area.room('kp_wet_basket_ledge', name='Wet Basket Ledge', desc='Woven baskets rest half-submerged along a ledge, keeping the catch alive and cool. Each carries a different colored handle, and an empty place at the end waits for a crew still working beyond the pockets.', room_type='clearing')
    kp_outer_kelp_fan = area.room('kp_outer_kelp_fan', name='Outer Kelp Fan', desc='Outer kelp spreads like a dark fan against the reef edge, trapping shells, bait scraps, and small angry life. Clearing this patch helps the fishing lane breathe without pretending the reef is tame.', room_type='clearing')
    kp_narrow_green_run = area.room('kp_narrow_green_run', name='Narrow Green Run', desc='A shoulder-wide run threads between dense weed beds, green light trembling over the bottom. Cut marks on one side and untouched nursery fronds on the other keep harvest traffic from crushing new growth.', room_type='clearing')
    kp_kelpbreak_rise = area.room('kp_kelpbreak_rise', name='Kelpbreak Rise', desc='The reef rises abruptly beyond the final pocket, forcing the kelp to break around bare stone. Drying racks and a coil of rescue line occupy the crest, where gatherers count one another before heading farther out.', room_type='clearing')
    wr_watch_reef = area.room('wr_watch_reef', name='Watch Reef', desc='Watch Reef lifts above the working flats, all dry shells, flag cords, and charcoal sail marks. Combat here belongs to civic defense: raider signs, blind cracks, and the discipline of seeing trouble early.', room_type='path')
    wr_lookout_shell_stack = area.room('wr_lookout_shell_stack', name='Lookout Shell Stack', desc='Conch shells are stacked mouth-down beneath a slab roof, dry and ready for the watch. Each size carries a different warning across the flats, and finger-worn labels make the sequence legible in darkness.', room_type='path')
    wr_charcoal_sail_stone = area.room('wr_charcoal_sail_stone', name='Charcoal Sail Stone', desc='Charcoal profiles of known sails cover a flat white stone: fishing rigs, courier wings, and the low dark canvas favored by raiders. Fresh strokes correct one silhouette where a mast was recently shortened.', room_type='path')
    wr_warning_flag_ridge = area.room('wr_warning_flag_ridge', name='Warning Flag Ridge', desc='Three high poles command the ridge, their signal flags rolled inside waxed covers. A red streamer already flies below them, telling crews that visibility beyond the eastern squall is uncertain.', room_type='path')
    wr_blind_side_crack = area.room('wr_blind_side_crack', name='Blind-Side Crack', desc='A crack cuts behind the clean sightline, just wide enough for raiders to shelter from the watch stones. Boot scars and snapped cord make the ambush logic visible before steel ever comes out.', room_type='path')
    wr_raider_boot_cut = area.room('wr_raider_boot_cut', name='Raider Boot Cut', desc="Boot cuts bite into the reef beside a dry shell cache, proof that raiders use this ridge when weather hides sails. Maku's watchers keep the place marked so practice and patrol share the same ground.", room_type='path')
    wr_high_foam_notch = area.room('wr_high_foam_notch', name='High Foam Notch', desc='A V-shaped notch frames the place where deep swells first break white over the outer reef. Watchers have scratched wind directions into the rim, pairing each with the number of breaths before foam reaches the lower shelves.', room_type='path')
    wr_open_water_seat = area.room('wr_open_water_seat', name='Open Water Seat', desc='A broad stone seat faces uninterrupted sea, polished by generations of rotating watches. A covered slate beneath it lists every canoe outside the reef and the colors expected on its returning sail.', room_type='path')
    wr_storm_color_view = area.room('wr_storm_color_view', name='Storm Color View', desc='The sea changes from bright blue to bruised green along a distant rain line. Colored chips set into the parapet give names to each shade and the preparations islanders make when it appears.', room_type='path')
    wr_signal_cord_post = area.room('wr_signal_cord_post', name='Signal Cord Post', desc='Braided cords run from this post toward the lower flats, carrying flag changes where a shell call would be lost in wind. One cord trembles under tension, relaying a message toward Korahei hand over hand.', room_type='path')
    wr_dry_shell_cache = area.room('wr_dry_shell_cache', name='Dry Shell Cache', desc='A stone box sealed with fish oil shelters spare signal shells, chalk, and waxed tinder. The inventory scratched inside its lid was updated today, including one cracked conch set aside for repair.', room_type='path')
    wr_sharp_coral_knuckle = area.room('wr_sharp_coral_knuckle', name='Sharp Coral Knuckle', desc='Jagged coral forces the ridge path through a narrow knuckle exposed to open water. Old rope rails have been replaced by a fresh double line, but blood-dark stains remain where a boarding party once climbed.', room_type='path')
    wr_wind_rattled_pole = area.room('wr_wind_rattled_pole', name='Wind-Rattled Pole', desc='Shell rings rattle against a tall pole with every shift in the wind. Watchers compare the rhythm to carved marks at its base, hearing sudden gusts before loose canvas farther down the reef can answer.', room_type='path')
    wr_far_canoe_sight = area.room('wr_far_canoe_sight', name='Far Canoe Sight', desc='A polished sighting groove aligns with the return channel miles beyond the flats. Two tiny sails sit within it now, one carrying the yellow flash of a fishing family expected before the tide turns.', room_type='path')
    wr_sentry_driftwood = area.room('wr_sentry_driftwood', name='Sentry Driftwood', desc='A massive driftwood trunk has been braced into a windbreak for the night sentry. Notches hold a lamp, a water jar, and a half-finished carving passed between generations of bored but vigilant hands.', room_type='path')
    wr_reef_shadow_edge = area.room('wr_reef_shadow_edge', name='Reef Shadow Edge', desc='Late light casts the ridge shadow across a lower channel invisible from the main watch. Broken reeds there move against the current, a small sign that something recently crossed beneath the blind edge.', room_type='path')
    wr_hooked_blade_scar = area.room('wr_hooked_blade_scar', name='Hooked Blade Scar', desc='Hooked blade scars score the coral where a lookout once forced raiders back toward open water. The ridge still funnels fights into a hard, readable line instead of scattering danger at random.', room_type='path')
    wr_rain_line_shelf = area.room('wr_rain_line_shelf', name='Rain Line Shelf', desc='Rain streaks leave pale lines on this high shelf, briefly hiding movement along the reef shadow. Raiders favor that weather, so the shelf has become a practical place to test readiness.', room_type='path')
    wr_wide_blue_turn = area.room('wr_wide_blue_turn', name='Wide Blue Turn', desc='The ridge swings outward around a wide reach of blue water where no sail can hide in reef glare. White stones mark measured distances, letting a lookout judge whether a strange hull is approaching or merely crossing the horizon.', room_type='path')
    wr_last_watch_stone = area.room('wr_last_watch_stone', name='Last Watch Stone', desc='The final watch stone bears handprints in ash from every sentry relieved at dawn. Beyond it the maintained ridge gives way to open reef, while behind it signal poles lead the eye all the way back to Korahei.', room_type='path')
    sr_sunscale_pool = area.room('sr_sunscale_pool', name='Sunscale Pool', desc='Gold-bright fish turn the pool into sparks while heavier tracks press the damp rim. The run promises food and good practice together, but the warm shallows make respect feel smarter than courage.', room_type='clearing')
    sr_golden_fish_run = area.room('sr_golden_fish_run', name='Golden Fish Run', desc='Sunscale snapper stream through a warm channel in a continuous golden ribbon. Shore drake tracks converge on both banks, with fresh tail marks showing where one waited beside the morning run.', room_type='clearing')
    sr_warm_shallow_cut = area.room('sr_warm_shallow_cut', name='Warm Shallow Cut', desc='Water heated over pale coral pours through a knee-deep cut into cooler pools. Small fish crowd the boundary, and the ripples around submerged ledges move even when the wind does not.', room_type='clearing')
    sr_broken_shell_bar = area.room('sr_broken_shell_bar', name='Broken Shell Bar', desc='A bar of cracked conch and turtle shell divides two feeding pools. Broad tooth marks score the largest pieces, while finer fragments have been swept into nests by reefcrawlers.', room_type='clearing')
    sr_heavy_reptile_track = area.room('sr_heavy_reptile_track', name='Heavy Reptile Track', desc='A heavy reptile trail crosses the shell bar at dawn and returns when the sun warms the stone. Bent grass, belly drag, and overlapping claw marks reveal a complete circuit between water, shade, and feeding ground.', room_type='clearing')
    sr_dawn_feeding_channel = area.room('sr_dawn_feeding_channel', name='Dawn Feeding Channel', desc='The eastern channel catches first light, drawing silver baitfish into a bright, crowded seam. Larger shapes hold in the blue beneath them until the tide lifts enough to strike.', room_type='clearing')
    sr_snapper_flash_bend = area.room('sr_snapper_flash_bend', name='Snapper Flash Bend', desc='The channel bends sharply around black reefstone and compresses the snapper run into a flashing wall. Scrapes on the inside curve mark where hunting reptiles launch, miss, and claw back onto the shelf.', room_type='clearing')
    sr_tide_eel_slot = area.room('sr_tide_eel_slot', name='Tide Eel Slot', desc='A narrow slot funnels tide eels, small fish, and the lizards that hunt both. Slick stone offers little footing near the mouth, but a dry shoulder above it provides room to watch the feeding order before descending.', room_type='clearing')
    sr_sun_hot_coral_back = area.room('sr_sun_hot_coral_back', name='Sun-Hot Coral Back', desc='A ridged spine of coral bakes above the water, warm enough to draw resting shore drakes. Shed scales cling to its rough crest, and every animal faces the same quick slide toward the deeper western pool.', room_type='clearing')
    sr_deep_blue_slash = area.room('sr_deep_blue_slash', name='Deep Blue Slash', desc='A straight blue fissure cuts through the pale reef as though opened in a single stroke. Fish vanish into its depth without slowing, followed by bubbles and the occasional pale curve of an eel.', room_type='clearing')
    sr_scale_spark_pool = area.room('sr_scale_spark_pool', name='Scale-Spark Pool', desc='Loose scales spin in a circular pool, catching sunlight like sparks around a drain. The current carries scent toward a shaded overhang where fresh claw marks gather at the waterline.', room_type='clearing')
    sr_foam_fed_turn = area.room('sr_foam_fed_turn', name='Foam-Fed Turn', desc='Every outer swell sends a tongue of foam around this sheltered bend. Stranded fish recover in the oxygen-rich wash, making the turn a dependable stop for hungry reef life after rough weather.', room_type='clearing')
    sr_low_predator_shelf = area.room('sr_low_predator_shelf', name='Low Predator Shelf', desc='The shelf sits low enough for feeding reptiles to climb out of sudden blue cuts. Broken shells warn where the last rush came from, making the danger feel ecological rather than decorative.', room_type='clearing')
    sr_outer_feeding_ring = area.room('sr_outer_feeding_ring', name='Outer Feeding Ring', desc='Fish flash inside a natural ring while lizards circle from the broken shell side. The feeding pattern repeats often enough for combat practice, but never so neatly that it feels like a pen.', room_type='clearing')
    sr_salt_breath_hollow = area.room('sr_salt_breath_hollow', name='Salt Breath Hollow', desc='Salt breath rises from a hollow where warm water moves under reefstone and shore drakes nose after stunned fish. The hollow is rewarding, loud, and risky in exactly the way far reef work should be.', room_type='clearing')
    sr_reefstone_knob = area.room('sr_reefstone_knob', name='Reefstone Knob', desc='A rounded knob rises above intersecting fish channels, offering a dry view in every direction. Scratches circle its base at several heights, left by creatures using the same refuge under different tides.', room_type='clearing')
    sr_shellcrack_crossing = area.room('sr_shellcrack_crossing', name='Shellcrack Crossing', desc='The route crosses a strip of shell that announces every step with a brittle crunch. Nearby predators know the sound; several trails angle toward the crossing from cover on both sides.', room_type='clearing')
    sr_wide_warm_basin = area.room('sr_wide_warm_basin', name='Wide Warm Basin', desc='A broad basin holds sun-warmed water long after the surrounding channels cool. Fish school along its shallow rim while heavier reptiles occupy the central shelf, each group keeping a wary distance.', room_type='clearing')
    sr_last_safe_pool = area.room('sr_last_safe_pool', name='Last Safe Pool', desc='White marker paint circles the last pool regularly checked by Korahei fishers. Beyond it, rescue cord ends, familiar harvest cuts disappear, and undisturbed tracks overlap around the water.', room_type='clearing')
    sr_open_reef_end = area.room('sr_open_reef_end', name='Open Reef End', desc='Maintained paths dissolve into open reef where warm channels meet the sea. Feeding calls, shell break, and moving water overlap without pause, and no marker promises which route will remain dry.', room_type='clearing')

    # Local exits
    area.exit(rl_korahei_landing, rl_landing_pole_shelf, 'east')
    area.exit(rl_landing_pole_shelf, rl_korahei_landing, 'west')
    area.exit(rl_landing_pole_shelf, rl_rope_wet_step, 'east')
    area.exit(rl_rope_wet_step, rl_landing_pole_shelf, 'west')
    area.exit(rl_rope_wet_step, rl_canoe_scar_stone, 'east')
    area.exit(rl_canoe_scar_stone, rl_rope_wet_step, 'west')
    area.exit(rl_canoe_scar_stone, rl_low_coral_ramp, 'east')
    area.exit(rl_low_coral_ramp, rl_canoe_scar_stone, 'west')
    area.exit(rl_low_coral_ramp, rl_shell_warning_cord, 'east')
    area.exit(rl_shell_warning_cord, rl_low_coral_ramp, 'west')
    area.exit(rl_shell_warning_cord, rl_silver_scale_crack, 'east')
    area.exit(rl_silver_scale_crack, rl_shell_warning_cord, 'west')
    area.exit(rl_silver_scale_crack, rl_barefoot_marker, 'east')
    area.exit(rl_barefoot_marker, rl_silver_scale_crack, 'west')
    area.exit(rl_barefoot_marker, rl_bright_foam_lip, 'east')
    area.exit(rl_bright_foam_lip, rl_barefoot_marker, 'west')
    area.exit(rl_bright_foam_lip, rl_kelp_dark_pocket, 'east')
    area.exit(rl_kelp_dark_pocket, rl_bright_foam_lip, 'west')
    area.exit(rl_kelp_dark_pocket, rl_tide_polished_turn, 'east')
    area.exit(rl_tide_polished_turn, rl_kelp_dark_pocket, 'west')
    area.exit(rl_tide_polished_turn, rl_reefbird_perch, 'east')
    area.exit(rl_reefbird_perch, rl_tide_polished_turn, 'west')
    area.exit(rl_reefbird_perch, rl_sun_slick_shelf, 'east')
    area.exit(rl_sun_slick_shelf, rl_reefbird_perch, 'west')
    area.exit(rl_sun_slick_shelf, rl_saltpalm_lean, 'east')
    area.exit(rl_saltpalm_lean, rl_sun_slick_shelf, 'west')
    area.exit(rl_saltpalm_lean, rl_old_mooring_peg, 'east')
    area.exit(rl_old_mooring_peg, rl_saltpalm_lean, 'west')
    area.exit(rl_old_mooring_peg, rl_basket_rest_stone, 'east')
    area.exit(rl_basket_rest_stone, rl_old_mooring_peg, 'west')
    area.exit(rl_basket_rest_stone, rl_fish_gut_rill, 'east')
    area.exit(rl_fish_gut_rill, rl_basket_rest_stone, 'west')
    area.exit(rl_fish_gut_rill, rl_safe_line_cairn, 'east')
    area.exit(rl_safe_line_cairn, rl_fish_gut_rill, 'west')
    area.exit(rl_safe_line_cairn, rl_outer_water_glance, 'east')
    area.exit(rl_outer_water_glance, rl_safe_line_cairn, 'west')
    area.exit(rl_outer_water_glance, rl_first_tide_fork, 'east')
    area.exit(rl_first_tide_fork, rl_outer_water_glance, 'west')
    area.exit(tm_tide_marker, tm_first_notch_stone, 'east')
    area.exit(tm_first_notch_stone, tm_tide_marker, 'west')
    area.exit(tm_first_notch_stone, tm_storm_line_marker, 'east')
    area.exit(tm_storm_line_marker, tm_first_notch_stone, 'west')
    area.exit(tm_storm_line_marker, tm_kelp_tied_cairn, 'east')
    area.exit(tm_kelp_tied_cairn, tm_storm_line_marker, 'west')
    area.exit(tm_kelp_tied_cairn, tm_fresh_seep_pool, 'east')
    area.exit(tm_fresh_seep_pool, tm_kelp_tied_cairn, 'west')
    area.exit(tm_fresh_seep_pool, tm_long_flat_shimmer, 'east')
    area.exit(tm_long_flat_shimmer, tm_fresh_seep_pool, 'west')
    area.exit(tm_long_flat_shimmer, tm_crawler_dotted_sand, 'east')
    area.exit(tm_crawler_dotted_sand, tm_long_flat_shimmer, 'west')
    area.exit(tm_crawler_dotted_sand, tm_white_shell_count, 'east')
    area.exit(tm_white_shell_count, tm_crawler_dotted_sand, 'west')
    area.exit(tm_white_shell_count, tm_marker_of_lost_nets, 'east')
    area.exit(tm_marker_of_lost_nets, tm_white_shell_count, 'west')
    area.exit(tm_marker_of_lost_nets, tm_second_tide_bend, 'east')
    area.exit(tm_second_tide_bend, tm_marker_of_lost_nets, 'west')
    area.exit(tm_second_tide_bend, tm_sun_dazzle_pool, 'east')
    area.exit(tm_sun_dazzle_pool, tm_second_tide_bend, 'west')
    area.exit(tm_sun_dazzle_pool, tm_low_warning_stake, 'east')
    area.exit(tm_low_warning_stake, tm_sun_dazzle_pool, 'west')
    area.exit(tm_low_warning_stake, tm_tide_mint_patch, 'east')
    area.exit(tm_tide_mint_patch, tm_low_warning_stake, 'west')
    area.exit(tm_tide_mint_patch, tm_salt_mirror_run, 'east')
    area.exit(tm_salt_mirror_run, tm_tide_mint_patch, 'west')
    area.exit(tm_salt_mirror_run, tm_fishers_chalk_post, 'east')
    area.exit(tm_fishers_chalk_post, tm_salt_mirror_run, 'west')
    area.exit(tm_fishers_chalk_post, tm_young_marker_stone, 'east')
    area.exit(tm_young_marker_stone, tm_fishers_chalk_post, 'west')
    area.exit(tm_young_marker_stone, tm_old_storm_scar, 'east')
    area.exit(tm_old_storm_scar, tm_young_marker_stone, 'west')
    area.exit(tm_old_storm_scar, tm_grey_crab_hollow, 'east')
    area.exit(tm_grey_crab_hollow, tm_old_storm_scar, 'west')
    area.exit(tm_grey_crab_hollow, tm_raised_sand_tongue, 'east')
    area.exit(tm_raised_sand_tongue, tm_grey_crab_hollow, 'west')
    area.exit(tm_raised_sand_tongue, tm_far_marker_rise, 'east')
    area.exit(tm_far_marker_rise, tm_raised_sand_tongue, 'west')
    area.exit(kp_fishing_shelf, kp_green_pocket_mouth, 'east')
    area.exit(kp_green_pocket_mouth, kp_fishing_shelf, 'west')
    area.exit(kp_green_pocket_mouth, kp_net_stake_lane, 'east')
    area.exit(kp_net_stake_lane, kp_green_pocket_mouth, 'west')
    area.exit(kp_net_stake_lane, kp_iodine_stone_seat, 'east')
    area.exit(kp_iodine_stone_seat, kp_net_stake_lane, 'west')
    area.exit(kp_iodine_stone_seat, kp_deep_kelp_window, 'east')
    area.exit(kp_deep_kelp_window, kp_iodine_stone_seat, 'west')
    area.exit(kp_deep_kelp_window, kp_silverjack_flicker, 'east')
    area.exit(kp_silverjack_flicker, kp_deep_kelp_window, 'west')
    area.exit(kp_silverjack_flicker, kp_half_tide_basin, 'east')
    area.exit(kp_half_tide_basin, kp_silverjack_flicker, 'west')
    area.exit(kp_half_tide_basin, kp_slick_round_seat, 'east')
    area.exit(kp_slick_round_seat, kp_half_tide_basin, 'west')
    area.exit(kp_slick_round_seat, kp_anglers_patience_rock, 'east')
    area.exit(kp_anglers_patience_rock, kp_slick_round_seat, 'west')
    area.exit(kp_anglers_patience_rock, kp_cut_kelp_mat, 'east')
    area.exit(kp_cut_kelp_mat, kp_anglers_patience_rock, 'west')
    area.exit(kp_cut_kelp_mat, kp_swaying_weed_gate, 'east')
    area.exit(kp_swaying_weed_gate, kp_cut_kelp_mat, 'west')
    area.exit(kp_swaying_weed_gate, kp_hidden_foot_pool, 'east')
    area.exit(kp_hidden_foot_pool, kp_swaying_weed_gate, 'west')
    area.exit(kp_hidden_foot_pool, kp_old_hook_crack, 'east')
    area.exit(kp_old_hook_crack, kp_hidden_foot_pool, 'west')
    area.exit(kp_old_hook_crack, kp_tide_eel_shade, 'east')
    area.exit(kp_tide_eel_shade, kp_old_hook_crack, 'west')
    area.exit(kp_tide_eel_shade, kp_pressed_kelp_slab, 'east')
    area.exit(kp_pressed_kelp_slab, kp_tide_eel_shade, 'west')
    area.exit(kp_pressed_kelp_slab, kp_fish_shadow_turn, 'east')
    area.exit(kp_fish_shadow_turn, kp_pressed_kelp_slab, 'west')
    area.exit(kp_fish_shadow_turn, kp_wet_basket_ledge, 'east')
    area.exit(kp_wet_basket_ledge, kp_fish_shadow_turn, 'west')
    area.exit(kp_wet_basket_ledge, kp_outer_kelp_fan, 'east')
    area.exit(kp_outer_kelp_fan, kp_wet_basket_ledge, 'west')
    area.exit(kp_outer_kelp_fan, kp_narrow_green_run, 'east')
    area.exit(kp_narrow_green_run, kp_outer_kelp_fan, 'west')
    area.exit(kp_narrow_green_run, kp_kelpbreak_rise, 'east')
    area.exit(kp_kelpbreak_rise, kp_narrow_green_run, 'west')
    area.exit(wr_watch_reef, wr_lookout_shell_stack, 'east')
    area.exit(wr_lookout_shell_stack, wr_watch_reef, 'west')
    area.exit(wr_lookout_shell_stack, wr_charcoal_sail_stone, 'east')
    area.exit(wr_charcoal_sail_stone, wr_lookout_shell_stack, 'west')
    area.exit(wr_charcoal_sail_stone, wr_warning_flag_ridge, 'east')
    area.exit(wr_warning_flag_ridge, wr_charcoal_sail_stone, 'west')
    area.exit(wr_warning_flag_ridge, wr_blind_side_crack, 'east')
    area.exit(wr_blind_side_crack, wr_warning_flag_ridge, 'west')
    area.exit(wr_blind_side_crack, wr_raider_boot_cut, 'east')
    area.exit(wr_raider_boot_cut, wr_blind_side_crack, 'west')
    area.exit(wr_raider_boot_cut, wr_high_foam_notch, 'east')
    area.exit(wr_high_foam_notch, wr_raider_boot_cut, 'west')
    area.exit(wr_high_foam_notch, wr_open_water_seat, 'east')
    area.exit(wr_open_water_seat, wr_high_foam_notch, 'west')
    area.exit(wr_open_water_seat, wr_storm_color_view, 'east')
    area.exit(wr_storm_color_view, wr_open_water_seat, 'west')
    area.exit(wr_storm_color_view, wr_signal_cord_post, 'east')
    area.exit(wr_signal_cord_post, wr_storm_color_view, 'west')
    area.exit(wr_signal_cord_post, wr_dry_shell_cache, 'east')
    area.exit(wr_dry_shell_cache, wr_signal_cord_post, 'west')
    area.exit(wr_dry_shell_cache, wr_sharp_coral_knuckle, 'east')
    area.exit(wr_sharp_coral_knuckle, wr_dry_shell_cache, 'west')
    area.exit(wr_sharp_coral_knuckle, wr_wind_rattled_pole, 'east')
    area.exit(wr_wind_rattled_pole, wr_sharp_coral_knuckle, 'west')
    area.exit(wr_wind_rattled_pole, wr_far_canoe_sight, 'east')
    area.exit(wr_far_canoe_sight, wr_wind_rattled_pole, 'west')
    area.exit(wr_far_canoe_sight, wr_sentry_driftwood, 'east')
    area.exit(wr_sentry_driftwood, wr_far_canoe_sight, 'west')
    area.exit(wr_sentry_driftwood, wr_reef_shadow_edge, 'east')
    area.exit(wr_reef_shadow_edge, wr_sentry_driftwood, 'west')
    area.exit(wr_reef_shadow_edge, wr_hooked_blade_scar, 'east')
    area.exit(wr_hooked_blade_scar, wr_reef_shadow_edge, 'west')
    area.exit(wr_hooked_blade_scar, wr_rain_line_shelf, 'east')
    area.exit(wr_rain_line_shelf, wr_hooked_blade_scar, 'west')
    area.exit(wr_rain_line_shelf, wr_wide_blue_turn, 'east')
    area.exit(wr_wide_blue_turn, wr_rain_line_shelf, 'west')
    area.exit(wr_wide_blue_turn, wr_last_watch_stone, 'east')
    area.exit(wr_last_watch_stone, wr_wide_blue_turn, 'west')
    area.exit(sr_sunscale_pool, sr_golden_fish_run, 'east')
    area.exit(sr_golden_fish_run, sr_sunscale_pool, 'west')
    area.exit(sr_golden_fish_run, sr_warm_shallow_cut, 'east')
    area.exit(sr_warm_shallow_cut, sr_golden_fish_run, 'west')
    area.exit(sr_warm_shallow_cut, sr_broken_shell_bar, 'east')
    area.exit(sr_broken_shell_bar, sr_warm_shallow_cut, 'west')
    area.exit(sr_broken_shell_bar, sr_heavy_reptile_track, 'east')
    area.exit(sr_heavy_reptile_track, sr_broken_shell_bar, 'west')
    area.exit(sr_heavy_reptile_track, sr_dawn_feeding_channel, 'east')
    area.exit(sr_dawn_feeding_channel, sr_heavy_reptile_track, 'west')
    area.exit(sr_dawn_feeding_channel, sr_snapper_flash_bend, 'east')
    area.exit(sr_snapper_flash_bend, sr_dawn_feeding_channel, 'west')
    area.exit(sr_snapper_flash_bend, sr_tide_eel_slot, 'east')
    area.exit(sr_tide_eel_slot, sr_snapper_flash_bend, 'west')
    area.exit(sr_tide_eel_slot, sr_sun_hot_coral_back, 'east')
    area.exit(sr_sun_hot_coral_back, sr_tide_eel_slot, 'west')
    area.exit(sr_sun_hot_coral_back, sr_deep_blue_slash, 'east')
    area.exit(sr_deep_blue_slash, sr_sun_hot_coral_back, 'west')
    area.exit(sr_deep_blue_slash, sr_scale_spark_pool, 'east')
    area.exit(sr_scale_spark_pool, sr_deep_blue_slash, 'west')
    area.exit(sr_scale_spark_pool, sr_foam_fed_turn, 'east')
    area.exit(sr_foam_fed_turn, sr_scale_spark_pool, 'west')
    area.exit(sr_foam_fed_turn, sr_low_predator_shelf, 'east')
    area.exit(sr_low_predator_shelf, sr_foam_fed_turn, 'west')
    area.exit(sr_low_predator_shelf, sr_outer_feeding_ring, 'east')
    area.exit(sr_outer_feeding_ring, sr_low_predator_shelf, 'west')
    area.exit(sr_outer_feeding_ring, sr_salt_breath_hollow, 'east')
    area.exit(sr_salt_breath_hollow, sr_outer_feeding_ring, 'west')
    area.exit(sr_salt_breath_hollow, sr_reefstone_knob, 'east')
    area.exit(sr_reefstone_knob, sr_salt_breath_hollow, 'west')
    area.exit(sr_reefstone_knob, sr_shellcrack_crossing, 'east')
    area.exit(sr_shellcrack_crossing, sr_reefstone_knob, 'west')
    area.exit(sr_shellcrack_crossing, sr_wide_warm_basin, 'east')
    area.exit(sr_wide_warm_basin, sr_shellcrack_crossing, 'west')
    area.exit(sr_wide_warm_basin, sr_last_safe_pool, 'east')
    area.exit(sr_last_safe_pool, sr_wide_warm_basin, 'west')
    area.exit(sr_last_safe_pool, sr_open_reef_end, 'east')
    area.exit(sr_open_reef_end, sr_last_safe_pool, 'west')
    area.exit(rl_first_tide_fork, tm_tide_marker, 'north')
    area.exit(tm_tide_marker, rl_first_tide_fork, 'south')
    area.exit(tm_far_marker_rise, kp_fishing_shelf, 'north')
    area.exit(kp_fishing_shelf, tm_far_marker_rise, 'south')
    area.exit(kp_kelpbreak_rise, wr_watch_reef, 'north')
    area.exit(wr_watch_reef, kp_kelpbreak_rise, 'south')
    area.exit(wr_last_watch_stone, sr_sunscale_pool, 'north')
    area.exit(sr_sunscale_pool, wr_last_watch_stone, 'south')
    area.exit(rl_korahei_landing, 'korahei:ac_reef_gate', 'west')

    # NPCs
    _reef_keeper = area.npc(tm_tide_marker, 'npc_reef_keeper_tavake', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Reef-Keeper Tavake studies you with open attention.'}, 'topics': {'help': 'Reads tide marks and turns errands into reef literacy.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Reef-Keeper Tavake adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})
    _fishing_mentor = area.npc(kp_fishing_shelf, 'npc_fishing_mentor_nae', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Fishing Mentor Nae studies you with open attention.'}, 'topics': {'help': 'Teaches patient fishing and why the best catch returns home.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Fishing Mentor Nae adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})
    _watch_maku = area.npc(wr_watch_reef, 'npc_wreck_watch_maku', faction='kauroran', dialogue={'greeting_tiers': {"neutral": 'Watch Maku studies you with open attention.'}, 'topics': {'help': 'Watches weather and raider signs without making fear the whole story.', 'custom': 'Korahei expects guests to learn by helping, listening, and returning what they carry.'}, 'base_hints': ['help', 'custom']}, ambient={'idle_echoes': ['Watch Maku adjusts a small detail, making the place easier for the next person.'], 'idle_interval': 90, 'idle_variance': 30})

    # Quest and delivery item templates
    area.item('reef_marker_rubbing', key='tide-marker rubbing', item_type='item', weight=0.1, rarity='normal', desc='A charcoal rubbing of tide marks that helps Tavake update the reef tally.', value=0, is_quest_item=True)
    area.quest(
        'reef_q_tide_marks',
        name='Reading the Tide Marks',
        description="Tavake turns Lani's tally into a guided walk through markers, pools, and warning stakes so the reef becomes legible.",
        quest_type='exploration',
        quest_giver='npc_reef_keeper_tavake',
        objectives=[{'type': 'investigate', 'target': 'tm_tide_marker', 'count': 1}, {'type': 'investigate', 'target': 'wr_watch_reef', 'count': 1}, {'type': 'collect', 'target': 'reef_kelp', 'count': 3}],
        rewards=[{'action_type': 'give_scales', 'amount': 28}, {'action_type': 'give_skill_xp', 'skill_id': 'fishing', 'count': 10}],
        next_quest_id='reef_q_net_righting',
        prerequisite_quests=['kor_q_reef_runner'],
        can_share=True,
        consequence_small='Tavake adds your rubbing to the tide board, turning one errand into better route warnings for every reef worker.',
    )
    area.quest(
        'reef_q_net_righting',
        name='Nets Righted, Not Replaced',
        description='Nae asks you to clear reefcrawlers from a repair shelf and gather shell pieces, tying combat to protecting shared tools.',
        quest_type='combat',
        quest_giver='npc_fishing_mentor_nae',
        objectives=[{'type': 'kill', 'target': 'reefcrawler', 'count': 4}, {'type': 'collect', 'target': 'reefcrawler_shell', 'count': 2}, {'type': 'investigate', 'target': 'kp_fishing_shelf', 'count': 1}],
        rewards=[{'action_type': 'give_scales', 'amount': 32}, {'action_type': 'give_skill_xp', 'skill_id': 'skinning', 'count': 8}],
        next_quest_id=None,
        prerequisite_quests=['reef_q_tide_marks'],
        can_share=True,
        consequence_small='Nae lashes your recovered shells into the net frame, and the repaired shelf stays open for fishers through the next tide.',
    )
    area.quest(
        'reef_q_fish_for_hearth',
        name='Fish for the Hearth',
        description='Nae invites you to catch fish for the open hearths, making fishing a contribution to Korahei rather than a disconnected chore.',
        quest_type='gathering',
        quest_giver='npc_fishing_mentor_nae',
        objectives=[{'type': 'collect', 'target': 'reef_silverjack', 'count': 3}, {'type': 'collect', 'target': 'sunscale_snapper', 'count': 1}, {'type': 'talk_to', 'target': 'npc_wreck_watch_maku', 'count': 1}],
        rewards=[{'action_type': 'give_scales', 'amount': 30}, {'action_type': 'give_skill_xp', 'skill_id': 'cooking', 'count': 8}],
        next_quest_id=None,
        prerequisite_quests=[],
        can_share=True,
        consequence_small='The hearth cooks call for the fish by your name, making the catch feel like shared supper rather than inventory.',
    )

    # Spawns
    area.spawn(tm_crawler_dotted_sand, 'reefcrawler', count_min=2, count_max=4, respawn_minutes=18)
    area.spawn(tm_grey_crab_hollow, 'reefcrawler', count_min=1, count_max=3, respawn_minutes=18)
    area.spawn(tm_raised_sand_tongue, 'reefcrawler', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(kp_hidden_foot_pool, 'reefcrawler', count_min=1, count_max=3, respawn_minutes=18)
    area.spawn(kp_tide_eel_shade, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(kp_outer_kelp_fan, 'reefcrawler', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(wr_raider_boot_cut, 'reef_raider', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(wr_blind_side_crack, 'reef_raider', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(wr_hooked_blade_scar, 'reef_raider', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(wr_rain_line_shelf, 'reef_raider', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(sr_heavy_reptile_track, 'shore_drake', count_min=1, count_max=1, respawn_minutes=18)
    area.spawn(sr_tide_eel_slot, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(sr_low_predator_shelf, 'shore_drake', count_min=1, count_max=1, respawn_minutes=18)
    area.spawn(sr_outer_feeding_ring, 'tideback_lizard', count_min=1, count_max=2, respawn_minutes=18)
    area.spawn(sr_salt_breath_hollow, 'shore_drake', count_min=1, count_max=1, respawn_minutes=18)

    # Gathering pools
    area.gathering_pool('fish', ['kp_fishing_shelf', 'sr_sunscale_pool', 'kp_tide_eel_shade'], ['reef_silverjack', 'tide_eel', 'sunscale_snapper'], max_active=3, respawn_minutes=12)
    area.gathering_pool('forage', ['kp_cut_kelp_mat', 'tm_tide_mint_patch'], ['reef_kelp'], max_active=3, respawn_minutes=12)
    area.gathering_pool('herb', ['tm_tide_mint_patch', 'rl_kelp_dark_pocket'], ['tide_mint'], max_active=3, respawn_minutes=12)
    area.gathering_pool('ore', ['sr_reefstone_knob', 'rl_low_coral_ramp'], ['reefstone'], max_active=3, respawn_minutes=12)
    area.gathering_pool('hide', ['tm_grey_crab_hollow', 'sr_heavy_reptile_track'], ['reefcrawler_shell', 'shore_drake_hide'], max_active=3, respawn_minutes=12)
    area.gathering_pool('wood', ['rl_saltpalm_lean', 'wr_sentry_driftwood'], ['saltpalm_wood'], max_active=3, respawn_minutes=12)

    return area.build()
