"""
Material definitions registry for Soravelon.

Pure-data module -- no Django or Evennia imports. Consumed by gathering_engine,
cmd_gathering, cmd_fishing, and crafting_definitions.

Defines the MATERIAL_REGISTRY taxonomy, material tiers, gathering categories,
gathering delay constants, visibility thresholds, and tool durability specs.
"""

# --- Material Tiers (D-10: 5 expandable tiers) ---

MATERIAL_TIERS = {
    1: "Common",
    2: "Uncommon",
    3: "Rare",
    4: "Exceptional",
    5: "Legendary",
}

# --- Gathering Categories (D-12, D-13, D-19) ---
# Maps category string to the skill, required tool, and command verb.

GATHERING_CATEGORIES = {
    "ore": {"skill": "mining", "tool": "pickaxe", "command": "mine"},
    "herb": {"skill": "herbalism", "tool": "sickle", "command": "harvest"},
    "wood": {"skill": "woodcutting", "tool": "hatchet", "command": "chop"},
    "forage": {"skill": "foraging", "tool": None, "command": "forage"},
    "fish": {"skill": "fishing", "tool": "fishing_rod", "command": "fish"},
    "hide": {"skill": "skinning", "tool": "skinning_knife", "command": "butcher"},
}

# --- Gathering Delay by Tier (base seconds, D-14) ---
# Skill reduces delay but never below 40% of these values.

GATHER_DELAY_BY_TIER = {
    1: 4,
    2: 6,
    3: 8,
    4: 12,
    5: 16,
}

# --- Visibility Thresholds (D-21) ---
# Minimum gathering skill required to see nodes at each visibility level.

VISIBILITY_THRESHOLDS = {
    "low": 0,
    "mid": 30,
    "high": 60,
}

# --- Tool Durability (D-19, D-20) ---
# max_durability = uses before breaking, repair_cost = Scales per repair.

TOOL_DURABILITY = {
    "pickaxe": {"max_durability": 50, "repair_cost": 5},
    "sickle": {"max_durability": 40, "repair_cost": 4},
    "hatchet": {"max_durability": 50, "repair_cost": 5},
    "skinning_knife": {"max_durability": 30, "repair_cost": 3},
    "fishing_rod": {"max_durability": 60, "repair_cost": 6},
}

# --- Material Registry (D-09, D-24, D-25) ---
# Central source of truth for all materials. Keyed by material_id.
# Each entry defines display name, category, tier, raw/processed forms,
# gathering/processing skill and station, and visibility level.

MATERIAL_REGISTRY = {

    # ===== Ores (mining) =====

    "iron_ore": {
        "display_name": "Iron Ore",
        "category": "ore",
        "tier": 1,
        "raw_form": "iron_ore",
        "processed_form": "iron_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "steel_ore": {
        "display_name": "Steel Ore",
        "category": "ore",
        "tier": 2,
        "raw_form": "steel_ore",
        "processed_form": "steel_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "mid",
    },
    "mithril_ore": {
        "display_name": "Mithril Ore",
        "category": "ore",
        "tier": 3,
        "raw_form": "mithril_ore",
        "processed_form": "mithril_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "high",
    },

    # ===== Herbs (herbalism) =====

    "wild_herb": {
        "display_name": "Wild Herb",
        "category": "herb",
        "tier": 1,
        "raw_form": "wild_herb",
        "processed_form": "herb_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "thornroot": {
        "display_name": "Thornroot",
        "category": "herb",
        "tier": 2,
        "raw_form": "thornroot",
        "processed_form": "thornroot_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "mid",
    },
    "moonpetal": {
        "display_name": "Moonpetal",
        "category": "herb",
        "tier": 3,
        "raw_form": "moonpetal",
        "processed_form": "moonpetal_essence",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "high",
    },

    # ===== Wood (woodcutting) =====

    "pine_log": {
        "display_name": "Pine Log",
        "category": "wood",
        "tier": 1,
        "raw_form": "pine_log",
        "processed_form": "pine_plank",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "oak_log": {
        "display_name": "Oak Log",
        "category": "wood",
        "tier": 2,
        "raw_form": "oak_log",
        "processed_form": "oak_plank",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "ironwood_log": {
        "display_name": "Ironwood Log",
        "category": "wood",
        "tier": 3,
        "raw_form": "ironwood_log",
        "processed_form": "ironwood_plank",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "high",
    },

    # ===== Forage (foraging) =====

    "wild_mushroom": {
        "display_name": "Wild Mushroom",
        "category": "forage",
        "tier": 1,
        "raw_form": "wild_mushroom",
        "processed_form": "dried_mushroom",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "cave_moss": {
        "display_name": "Cave Moss",
        "category": "forage",
        "tier": 2,
        "raw_form": "cave_moss",
        "processed_form": "moss_paste",
        "gathering_skill": "foraging",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "mid",
    },
    "starbloom": {
        "display_name": "Starbloom",
        "category": "forage",
        "tier": 3,
        "raw_form": "starbloom",
        "processed_form": "starbloom_powder",
        "gathering_skill": "foraging",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "high",
    },

    # ===== Fish (fishing) =====

    "river_trout": {
        "display_name": "River Trout",
        "category": "fish",
        "tier": 1,
        "raw_form": "river_trout",
        "processed_form": "raw_fish",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "cave_eel": {
        "display_name": "Cave Eel",
        "category": "fish",
        "tier": 2,
        "raw_form": "cave_eel",
        "processed_form": "eel_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "shadow_bass": {
        "display_name": "Shadow Bass",
        "category": "fish",
        "tier": 3,
        "raw_form": "shadow_bass",
        "processed_form": "shadow_bass_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "high",
    },

    # ===== Hides (skinning) =====

    "boar_hide": {
        "display_name": "Boar Hide",
        "category": "hide",
        "tier": 1,
        "raw_form": "boar_hide",
        "processed_form": "leather_strip",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "ash_wolf_pelt": {
        "display_name": "Ash Wolf Pelt",
        "category": "hide",
        "tier": 2,
        "raw_form": "ash_wolf_pelt",
        "processed_form": "cured_pelt",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "drake_scale": {
        "display_name": "Drake Scale",
        "category": "hide",
        "tier": 3,
        "raw_form": "drake_scale",
        "processed_form": "treated_scale",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "high",
    },

    # ===== Zone-specific materials (Ashreach Plains) =====

    "wolfsbane": {
        "display_name": "Wolfsbane",
        "category": "herb",
        "tier": 1,
        "raw_form": "wolfsbane",
        "processed_form": "wolfsbane_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "ashgrass_fiber": {
        "display_name": "Ashgrass Fiber",
        "category": "forage",
        "tier": 1,
        "raw_form": "ashgrass_fiber",
        "processed_form": "woven_ashgrass",
        "gathering_skill": "foraging",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "flint_shard": {
        "display_name": "Flint Shard",
        "category": "ore",
        "tier": 1,
        "raw_form": "flint_shard",
        "processed_form": "knapped_flint",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Reth Foothills) =====

    "copper_ore": {
        "display_name": "Copper Ore",
        "category": "ore",
        "tier": 1,
        "raw_form": "copper_ore",
        "processed_form": "copper_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "mountain_herb": {
        "display_name": "Mountain Herb",
        "category": "herb",
        "tier": 1,
        "raw_form": "mountain_herb",
        "processed_form": "mountain_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Stormhaven Coast) =====

    "salt": {
        "display_name": "Sea Salt",
        "category": "forage",
        "tier": 1,
        "raw_form": "salt",
        "processed_form": "refined_salt",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "driftwood": {
        "display_name": "Driftwood",
        "category": "wood",
        "tier": 1,
        "raw_form": "driftwood",
        "processed_form": "driftwood_plank",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "sea_glass": {
        "display_name": "Sea Glass",
        "category": "forage",
        "tier": 1,
        "raw_form": "sea_glass",
        "processed_form": "polished_glass",
        "gathering_skill": "foraging",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "coral_fragment": {
        "display_name": "Coral Fragment",
        "category": "ore",
        "tier": 1,
        "raw_form": "coral_fragment",
        "processed_form": "coral_dust",
        "gathering_skill": "mining",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Vael's Crossing) =====

    "common_herb": {
        "display_name": "Common Herb",
        "category": "herb",
        "tier": 1,
        "raw_form": "common_herb",
        "processed_form": "herb_poultice",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "rough_leather": {
        "display_name": "Rough Leather",
        "category": "hide",
        "tier": 1,
        "raw_form": "rough_leather",
        "processed_form": "leather_strip",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Cantera Edge) =====

    "cantera_timber": {
        "display_name": "Cantera Timber",
        "category": "wood",
        "tier": 1,
        "raw_form": "cantera_timber",
        "processed_form": "cantera_plank",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "nightcap_mushroom": {
        "display_name": "Nightcap Mushroom",
        "category": "forage",
        "tier": 1,
        "raw_form": "nightcap_mushroom",
        "processed_form": "dried_nightcap",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "bramble_berry": {
        "display_name": "Bramble Berry",
        "category": "forage",
        "tier": 1,
        "raw_form": "bramble_berry",
        "processed_form": "bramble_jam",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "cantera_amber": {
        "display_name": "Cantera Amber",
        "category": "ore",
        "tier": 2,
        "raw_form": "cantera_amber",
        "processed_form": "polished_amber",
        "gathering_skill": "mining",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "shelf_fungus": {
        "display_name": "Shelf Fungus",
        "category": "forage",
        "tier": 1,
        "raw_form": "shelf_fungus",
        "processed_form": "fungus_powder",
        "gathering_skill": "foraging",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "spider_silk": {
        "display_name": "Spider Silk",
        "category": "hide",
        "tier": 2,
        "raw_form": "spider_silk",
        "processed_form": "silk_thread",
        "gathering_skill": "skinning",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "pala_bark": {
        "display_name": "Pala Bark",
        "category": "wood",
        "tier": 2,
        "raw_form": "pala_bark",
        "processed_form": "pala_strip",
        "gathering_skill": "woodcutting",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "mid",
    },
    "pala_sap": {
        "display_name": "Pala Sap",
        "category": "forage",
        "tier": 3,
        "raw_form": "pala_sap",
        "processed_form": "pala_resin",
        "gathering_skill": "foraging",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "high",
    },
    "cave_mushroom": {
        "display_name": "Cave Mushroom",
        "category": "forage",
        "tier": 1,
        "raw_form": "cave_mushroom",
        "processed_form": "dried_cave_mushroom",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "resonance_crystal": {
        "display_name": "Resonance Crystal",
        "category": "ore",
        "tier": 3,
        "raw_form": "resonance_crystal",
        "processed_form": "attuned_crystal",
        "gathering_skill": "mining",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "high",
    },

    # ===== Zone-specific materials (Hub 4: Crownroad North) =====

    "roadsage": {
        "display_name": "Roadsage",
        "category": "herb",
        "tier": 1,
        "raw_form": "roadsage",
        "processed_form": "roadsage_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "mileglass_lichen": {
        "display_name": "Mileglass Lichen",
        "category": "herb",
        "tier": 1,
        "raw_form": "mileglass_lichen",
        "processed_form": "mileglass_powder",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "milestone_iron": {
        "display_name": "Milestone Iron",
        "category": "ore",
        "tier": 1,
        "raw_form": "milestone_iron",
        "processed_form": "reclaimed_iron_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "relay_scrap": {
        "display_name": "Relay Scrap",
        "category": "ore",
        "tier": 1,
        "raw_form": "relay_scrap",
        "processed_form": "sorted_relay_scrap",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "charter_reed": {
        "display_name": "Charter Reed",
        "category": "forage",
        "tier": 1,
        "raw_form": "charter_reed",
        "processed_form": "dried_charter_reed",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "dust_hound_hide": {
        "display_name": "Dust Hound Hide",
        "category": "hide",
        "tier": 1,
        "raw_form": "dust_hound_hide",
        "processed_form": "cured_dust_hound_hide",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Hub 4: Old Causeway) =====

    "causeway_shard": {
        "display_name": "Causeway Shard",
        "category": "ore",
        "tier": 1,
        "raw_form": "causeway_shard",
        "processed_form": "trimmed_causeway_shard",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "archmoss": {
        "display_name": "Archmoss",
        "category": "herb",
        "tier": 1,
        "raw_form": "archmoss",
        "processed_form": "archmoss_paste",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "cistern_salt": {
        "display_name": "Cistern Salt",
        "category": "forage",
        "tier": 1,
        "raw_form": "cistern_salt",
        "processed_form": "washed_cistern_salt",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "survey_bronze": {
        "display_name": "Survey Bronze",
        "category": "ore",
        "tier": 1,
        "raw_form": "survey_bronze",
        "processed_form": "survey_bronze_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "reservoir_calcite": {
        "display_name": "Reservoir Calcite",
        "category": "ore",
        "tier": 1,
        "raw_form": "reservoir_calcite",
        "processed_form": "powdered_reservoir_calcite",
        "gathering_skill": "mining",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "shrine_silt": {
        "display_name": "Shrine Silt",
        "category": "herb",
        "tier": 1,
        "raw_form": "shrine_silt",
        "processed_form": "settled_shrine_silt",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Hub 4: Ironvein Escarpment) =====

    "ironvein_ore": {
        "display_name": "Ironvein Ore",
        "category": "ore",
        "tier": 1,
        "raw_form": "ironvein_ore",
        "processed_form": "ironvein_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "bench_slate": {
        "display_name": "Bench Slate",
        "category": "ore",
        "tier": 1,
        "raw_form": "bench_slate",
        "processed_form": "cut_bench_slate",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "haul_chain_link": {
        "display_name": "Haul Chain Link",
        "category": "forage",
        "tier": 1,
        "raw_form": "haul_chain_link",
        "processed_form": "sorted_chain_link",
        "gathering_skill": "foraging",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "runoff_cress": {
        "display_name": "Runoff Cress",
        "category": "herb",
        "tier": 1,
        "raw_form": "runoff_cress",
        "processed_form": "runoff_cress_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "memorial_chalk": {
        "display_name": "Memorial Chalk",
        "category": "forage",
        "tier": 1,
        "raw_form": "memorial_chalk",
        "processed_form": "ground_memorial_chalk",
        "gathering_skill": "foraging",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "slag_hound_hide": {
        "display_name": "Slag Hound Hide",
        "category": "hide",
        "tier": 1,
        "raw_form": "slag_hound_hide",
        "processed_form": "cured_slag_hound_hide",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Hub 4: Stagcrown Preserve) =====

    "horncap_moss": {
        "display_name": "Horncap Moss",
        "category": "herb",
        "tier": 1,
        "raw_form": "horncap_moss",
        "processed_form": "horncap_paste",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "charter_bark": {
        "display_name": "Charter Bark",
        "category": "herb",
        "tier": 1,
        "raw_form": "charter_bark",
        "processed_form": "charter_bark_powder",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "stagcrown_hide": {
        "display_name": "Stagcrown Hide",
        "category": "hide",
        "tier": 1,
        "raw_form": "stagcrown_hide",
        "processed_form": "cured_stagcrown_hide",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "silverfin_trout": {
        "display_name": "Silverfin Trout",
        "category": "fish",
        "tier": 1,
        "raw_form": "silverfin_trout",
        "processed_form": "silverfin_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "keeper_reed": {
        "display_name": "Keeper Reed",
        "category": "forage",
        "tier": 1,
        "raw_form": "keeper_reed",
        "processed_form": "dried_keeper_reed",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "bone_lure": {
        "display_name": "Bone Lure",
        "category": "forage",
        "tier": 1,
        "raw_form": "bone_lure",
        "processed_form": "polished_bone_lure",
        "gathering_skill": "foraging",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Hub 3: Tremeneth) =====

    "greyteeth_iron": {
        "display_name": "Greyteeth Iron",
        "category": "ore",
        "tier": 2,
        "raw_form": "greyteeth_iron",
        "processed_form": "greyteeth_iron_ingot",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "mid",
    },
    "coldvein_stone": {
        "display_name": "Coldvein Stone",
        "category": "ore",
        "tier": 2,
        "raw_form": "coldvein_stone",
        "processed_form": "cut_coldvein_stone",
        "gathering_skill": "mining",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "pressure_quartz": {
        "display_name": "Pressure Quartz",
        "category": "ore",
        "tier": 3,
        "raw_form": "pressure_quartz",
        "processed_form": "faceted_pressure_quartz",
        "gathering_skill": "mining",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "high",
    },
    "resonance_shard": {
        "display_name": "Resonance Shard",
        "category": "ore",
        "tier": 3,
        "raw_form": "resonance_shard",
        "processed_form": "attuned_resonance_shard",
        "gathering_skill": "mining",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "high",
    },
    "windroot": {
        "display_name": "Windroot",
        "category": "herb",
        "tier": 2,
        "raw_form": "windroot",
        "processed_form": "windroot_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "mid",
    },
    "bellcap_mushroom": {
        "display_name": "Bellcap Mushroom",
        "category": "forage",
        "tier": 2,
        "raw_form": "bellcap_mushroom",
        "processed_form": "dried_bellcap",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "haul_rope_fiber": {
        "display_name": "Haul-Rope Fiber",
        "category": "forage",
        "tier": 1,
        "raw_form": "haul_rope_fiber",
        "processed_form": "twisted_haul_rope_fiber",
        "gathering_skill": "foraging",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "snowmelt_trout": {
        "display_name": "Snowmelt Trout",
        "category": "fish",
        "tier": 2,
        "raw_form": "snowmelt_trout",
        "processed_form": "snowmelt_trout_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "blackwater_char": {
        "display_name": "Blackwater Char",
        "category": "fish",
        "tier": 3,
        "raw_form": "blackwater_char",
        "processed_form": "blackwater_char_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "high",
    },
    "cavern_whitefish": {
        "display_name": "Cavern Whitefish",
        "category": "fish",
        "tier": 2,
        "raw_form": "cavern_whitefish",
        "processed_form": "cavern_whitefish_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "ridgecat_pelt": {
        "display_name": "Ridgecat Pelt",
        "category": "hide",
        "tier": 2,
        "raw_form": "ridgecat_pelt",
        "processed_form": "cured_ridgecat_pelt",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "minevermin_hide": {
        "display_name": "Minevermin Hide",
        "category": "hide",
        "tier": 1,
        "raw_form": "minevermin_hide",
        "processed_form": "cured_minevermin_hide",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },

    # ===== Zone-specific materials (Hub 5: Korahei and Velu'ana) =====

    "reef_silverjack": {
        "display_name": "Reef Silverjack",
        "category": "fish",
        "tier": 1,
        "raw_form": "reef_silverjack",
        "processed_form": "silverjack_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "tide_eel": {
        "display_name": "Tide Eel",
        "category": "fish",
        "tier": 2,
        "raw_form": "tide_eel",
        "processed_form": "tide_eel_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "sunscale_snapper": {
        "display_name": "Sunscale Snapper",
        "category": "fish",
        "tier": 2,
        "raw_form": "sunscale_snapper",
        "processed_form": "sunscale_snapper_fillet",
        "gathering_skill": "fishing",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "saltfruit": {
        "display_name": "Saltfruit",
        "category": "forage",
        "tier": 1,
        "raw_form": "saltfruit",
        "processed_form": "dried_saltfruit",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "reef_kelp": {
        "display_name": "Reef Kelp",
        "category": "forage",
        "tier": 1,
        "raw_form": "reef_kelp",
        "processed_form": "pressed_reef_kelp",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "shellbean": {
        "display_name": "Shellbean",
        "category": "forage",
        "tier": 1,
        "raw_form": "shellbean",
        "processed_form": "roasted_shellbean",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "low",
    },
    "hearthroot": {
        "display_name": "Hearthroot",
        "category": "forage",
        "tier": 2,
        "raw_form": "hearthroot",
        "processed_form": "braised_hearthroot",
        "gathering_skill": "foraging",
        "processing_skill": "cooking",
        "processing_station": "campfire",
        "visibility": "mid",
    },
    "sunleaf": {
        "display_name": "Sunleaf",
        "category": "herb",
        "tier": 1,
        "raw_form": "sunleaf",
        "processed_form": "sunleaf_extract",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "kiai_blossom": {
        "display_name": "Kiai Blossom",
        "category": "herb",
        "tier": 2,
        "raw_form": "kiai_blossom",
        "processed_form": "kiai_blossom_tincture",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "mid",
    },
    "tide_mint": {
        "display_name": "Tide Mint",
        "category": "herb",
        "tier": 1,
        "raw_form": "tide_mint",
        "processed_form": "tide_mint_oil",
        "gathering_skill": "herbalism",
        "processing_skill": "alchemy",
        "processing_station": "alchemy_bench",
        "visibility": "low",
    },
    "blackglass_shard": {
        "display_name": "Blackglass Shard",
        "category": "ore",
        "tier": 2,
        "raw_form": "blackglass_shard",
        "processed_form": "blackglass_sliver",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "mid",
    },
    "reefstone": {
        "display_name": "Reefstone",
        "category": "ore",
        "tier": 1,
        "raw_form": "reefstone",
        "processed_form": "cut_reefstone",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "low",
    },
    "old_ring_basalt": {
        "display_name": "Old Ring Basalt",
        "category": "ore",
        "tier": 2,
        "raw_form": "old_ring_basalt",
        "processed_form": "polished_ring_basalt",
        "gathering_skill": "mining",
        "processing_skill": "smithing",
        "processing_station": "forge",
        "visibility": "mid",
    },
    "reefcrawler_shell": {
        "display_name": "Reefcrawler Shell",
        "category": "hide",
        "tier": 1,
        "raw_form": "reefcrawler_shell",
        "processed_form": "polished_reefcrawler_shell",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "shore_drake_hide": {
        "display_name": "Shore Drake Hide",
        "category": "hide",
        "tier": 2,
        "raw_form": "shore_drake_hide",
        "processed_form": "cured_shore_drake_hide",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "braided_scale_shed": {
        "display_name": "Braided Scale Shed",
        "category": "hide",
        "tier": 2,
        "raw_form": "braided_scale_shed",
        "processed_form": "braided_scale_leather",
        "gathering_skill": "skinning",
        "processing_skill": "smithing",
        "processing_station": "workbench",
        "visibility": "mid",
    },
    "saltpalm_wood": {
        "display_name": "Saltpalm Wood",
        "category": "wood",
        "tier": 1,
        "raw_form": "saltpalm_wood",
        "processed_form": "saltpalm_plank",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "low",
    },
    "circle_bamboo": {
        "display_name": "Circle Bamboo",
        "category": "wood",
        "tier": 2,
        "raw_form": "circle_bamboo",
        "processed_form": "split_circle_bamboo",
        "gathering_skill": "woodcutting",
        "processing_skill": "engineering",
        "processing_station": "workbench",
        "visibility": "mid",
    },
}
