"""
Primary skill affordance registry for Soravelon.

These are the repeatable, real-situation verbs each skill should grow from.
They are deliberately not called abilities because Soravelon already uses that
term for domain/combat powers.
"""

PRIMARY_SKILL_AFFORDANCES = {
    "lockpicking": {
        "primary_verb": "pick",
        "system": "locked doors, chests, cages, and old mechanisms",
        "repeatability": "contextual locked targets",
        "anti_farming_gate": "requires an unresolved lock target and consumes tool durability or target state",
        "implementation_status": "planned",
    },
    "animal_handling": {
        "primary_verb": "calm",
        "system": "mundane animals and beast-type encounters",
        "repeatability": "contextual creature interactions",
        "anti_farming_gate": "requires a valid animal/beast target with disposition or encounter pressure",
        "implementation_status": "planned",
    },
    "beast_training": {
        "primary_verb": "condition",
        "system": "companion and trained beast behaviors",
        "repeatability": "companion-session gated",
        "anti_farming_gate": "requires companion ownership/state, time, food, or task slots",
        "implementation_status": "planned_companions",
    },
    "herbalism": {
        "primary_verb": "harvest",
        "system": "herb gathering nodes and medicinal plant identification",
        "repeatability": "resource-node gated",
        "anti_farming_gate": "requires spawned herb nodes with depletion and respawn timers",
        "implementation_status": "live",
    },
    "tracking": {
        "primary_verb": "track",
        "system": "tracks, spoor, patrol traces, quest trails, and creature sign",
        "repeatability": "contextual trail targets",
        "anti_farming_gate": "requires active room/quest/creature trail state and resolves or advances it",
        "implementation_status": "planned",
    },
    "climbing": {
        "primary_verb": "climb",
        "system": "ledges, cliff routes, rescue points, and vertical shortcuts",
        "repeatability": "route and hazard gated",
        "anti_farming_gate": "requires authored climb target, risk, route state, or traversal consequence",
        "implementation_status": "planned",
    },
    "persuasion": {
        "primary_verb": "persuade",
        "system": "dialogue pressure, favors, quest alternatives, and faction asks",
        "repeatability": "NPC-state gated",
        "anti_farming_gate": "requires NPC topic/state and records the social attempt outcome",
        "implementation_status": "planned",
    },
    "intimidation": {
        "primary_verb": "pressure",
        "system": "threat posture in dialogue, patrols, standoffs, and enemy morale",
        "repeatability": "NPC/combat-state gated",
        "anti_farming_gate": "requires a target with morale, standing, or encounter state and records consequences",
        "implementation_status": "planned",
    },
    "swimming": {
        "primary_verb": "swim",
        "system": "water crossings, dives, currents, and recovery routes",
        "repeatability": "route and hazard gated",
        "anti_farming_gate": "requires water room state, stamina pressure, or destination progress",
        "implementation_status": "planned",
    },
    "first_aid": {
        "primary_verb": "tend",
        "system": "wounded characters, field injuries, bleeding, and recovery support",
        "repeatability": "injury-state gated",
        "anti_farming_gate": "requires untreated injury, supplies, cooldown, or recovery state",
        "implementation_status": "planned",
    },
    "appraisal": {
        "primary_verb": "inspect",
        "system": "item inspection, quality, value, properties, and comparison",
        "repeatability": "item-contextual",
        "anti_farming_gate": "requires item targets; passive gain comes from successful item inspection",
        "implementation_status": "live",
    },
    "stealth": {
        "primary_verb": "sneak",
        "system": "patrol avoidance, ambush setup, guarded spaces, and hidden movement",
        "repeatability": "encounter/room-state gated",
        "anti_farming_gate": "requires observers, patrols, lighting, route state, or exposure risk",
        "implementation_status": "planned",
    },
    "foraging": {
        "primary_verb": "forage",
        "system": "wild food, water, fibers, and useful roadside materials",
        "repeatability": "resource-node gated",
        "anti_farming_gate": "requires spawned forage nodes with depletion and respawn timers",
        "implementation_status": "live",
    },
    "survival": {
        "primary_verb": "camp",
        "system": "safe rest, shelter reading, environmental pressure, and route preparation",
        "repeatability": "environment-state gated",
        "anti_farming_gate": "requires wilderness pressure, supplies, travel state, or rest cooldown",
        "implementation_status": "planned",
    },
    "node_reading": {
        "primary_verb": "read",
        "system": "node state, failure pressure, safe paths, and magical infrastructure",
        "repeatability": "node-state gated",
        "anti_farming_gate": "requires active node/room-state context and reports current state rather than raw XP",
        "implementation_status": "planned",
    },
    "navigation": {
        "primary_verb": "chart",
        "system": "routes, landmarks, maps, fog, underground spaces, and wayfinding",
        "repeatability": "route-state gated",
        "anti_farming_gate": "requires route uncertainty, map target, landmark, or travel progress",
        "implementation_status": "planned",
    },
    "fishing": {
        "primary_verb": "fish",
        "system": "fish gathering nodes, bait, water quality, and catch results",
        "repeatability": "resource-node gated",
        "anti_farming_gate": "requires spawned fish nodes, tool state, bait, depletion, and respawn timers",
        "implementation_status": "live",
    },
    "engineering": {
        "primary_verb": "craft",
        "system": "workbench recipes, machines, field devices, bridges, braces, and traps",
        "repeatability": "recipe/resource gated",
        "anti_farming_gate": "requires recipe, workbench, ingredients, craft time, or authored work order",
        "implementation_status": "live",
    },
    "cooking": {
        "primary_verb": "cook",
        "system": "campfire recipes, meals, rations, buffs, and food prep",
        "repeatability": "recipe/resource gated",
        "anti_farming_gate": "requires recipe, station, ingredients, and craft time",
        "implementation_status": "live",
    },
    "smithing": {
        "primary_verb": "smith",
        "system": "metalworking recipes, repairs, weapons, armor, and prospecting",
        "repeatability": "recipe/resource gated",
        "anti_farming_gate": "requires recipe, station, ingredients, repair target, or deposit",
        "implementation_status": "live",
    },
    "alchemy": {
        "primary_verb": "brew",
        "system": "alchemy recipes, reagents, potions, antidotes, and benches",
        "repeatability": "recipe/resource gated",
        "anti_farming_gate": "requires recipe, station, ingredients, and craft time",
        "implementation_status": "live",
    },
    "reflexes": {
        "primary_verb": "evade",
        "system": "hazards, ambushes, telegraphed attacks, and reaction checks",
        "repeatability": "danger-state gated",
        "anti_farming_gate": "requires active hazard/combat/ambush state and resolves a real threat",
        "implementation_status": "planned",
    },
    "investigation": {
        "primary_verb": "search",
        "system": "hidden exits, lore fragments, concealed objects, and crime scenes",
        "repeatability": "room/object-state gated",
        "anti_farming_gate": "requires searchable room/object context; discoveries can resolve or move state",
        "implementation_status": "live",
    },
    "scholarship": {
        "primary_verb": "study",
        "system": "records, inscriptions, maps, archives, and contradictory accounts",
        "repeatability": "knowledge-target gated",
        "anti_farming_gate": "requires authored text/artifact/context and records what has been understood",
        "implementation_status": "planned",
    },
    "mining": {
        "primary_verb": "mine",
        "system": "ore and stone gathering nodes",
        "repeatability": "resource-node gated",
        "anti_farming_gate": "requires spawned ore nodes with depletion, tool durability, and respawn timers",
        "implementation_status": "live",
    },
    "woodcutting": {
        "primary_verb": "chop",
        "system": "wood gathering nodes and timber harvesting",
        "repeatability": "resource-node gated",
        "anti_farming_gate": "requires spawned wood nodes with depletion, tool durability, and respawn timers",
        "implementation_status": "live",
    },
    "skinning": {
        "primary_verb": "butcher",
        "system": "corpse harvesting, hides, bones, sinew, and creature remains",
        "repeatability": "corpse-state gated",
        "anti_farming_gate": "requires unbutchered corpse state and marks the corpse as butchered",
        "implementation_status": "live",
    },
    "leatherworking": {
        "primary_verb": "tan",
        "system": "hide curing, straps, leather repairs, and fitted leather gear",
        "repeatability": "recipe/resource gated",
        "anti_farming_gate": "requires hide materials, work surface, recipe/task, and craft time",
        "implementation_status": "planned",
    },
    "weapon_blades": {
        "primary_verb": "attack",
        "system": "blade attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_axes": {
        "primary_verb": "attack",
        "system": "axe attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_hafted": {
        "primary_verb": "attack",
        "system": "hafted weapon attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_polearms": {
        "primary_verb": "attack",
        "system": "polearm attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_bows": {
        "primary_verb": "attack",
        "system": "bow attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_thrown": {
        "primary_verb": "attack",
        "system": "thrown weapon attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_staves": {
        "primary_verb": "attack",
        "system": "staff attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_shields": {
        "primary_verb": "attack",
        "system": "shield attacks and shield-forward combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
    "weapon_unarmed": {
        "primary_verb": "attack",
        "system": "unarmed attacks in combat",
        "repeatability": "combat-state gated",
        "anti_farming_gate": "requires valid combat target and successful attack flow",
        "implementation_status": "live",
    },
}


def get_primary_skill_affordance(skill_id):
    """Return the primary repeatable affordance metadata for a skill id."""
    return PRIMARY_SKILL_AFFORDANCES.get(skill_id)
