# Generated by Django 6.0.3 on 2026-03-21 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("objects", "0015_soravelonobject_soravelonitem_soraveloncontainer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("home_hub", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="objects.objectdb",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NodeEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_id", models.CharField(max_length=64)),
                ("node_type", models.CharField(max_length=32)),
                ("event_type", models.CharField(max_length=32)),
                ("failure_at_event", models.FloatField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "triggered_by",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["zone_id", "occurred_at"],
                        name="world_nodee_zone_id_49ca91_idx",
                    ),
                    models.Index(
                        fields=["node_type", "event_type"],
                        name="world_nodee_node_ty_a8e11c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_type", models.CharField(max_length=32)),
                ("amount", models.IntegerField()),
                ("balance_after", models.IntegerField()),
                ("description", models.CharField(blank=True, max_length=256)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("related_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character_id", "occurred_at"],
                        name="world_bankt_charact_b54879_idx",
                    ),
                    models.Index(
                        fields=["character_id", "transaction_type"],
                        name="world_bankt_charact_7f066f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.CharField(max_length=128)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("general", "General Proficiency"),
                            ("zone_attunement", "Zone Attunement"),
                            ("node_attunement", "Node Attunement"),
                            ("creature_attunement", "Creature Attunement"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.FloatField(default=0.0)),
                ("last_practiced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character", "skill_type"],
                        name="world_chara_charact_32d5b6_idx",
                    )
                ],
                "unique_together": {("character", "skill_id")},
            },
        ),
        migrations.CreateModel(
            name="DebtRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("deadline_playtime_seconds", models.IntegerField()),
                ("status", models.CharField(default="active", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_records",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character_id", "status"],
                        name="world_debtr_charact_198e67_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FactionStanding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("faction_id", models.CharField(db_index=True, max_length=64)),
                (
                    "subfaction_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("standing", models.IntegerField(default=0)),
                ("trust", models.IntegerField(default=50)),
                ("betrayal_flag", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faction_standings",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["faction_id", "subfaction_id", "standing"],
                        name="world_facti_faction_80ebd8_idx",
                    )
                ],
                "unique_together": {("character", "faction_id", "subfaction_id")},
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.IntegerField(unique=True)),
                ("quantity", models.IntegerField(default=1)),
                ("container_id", models.IntegerField(blank=True, null=True)),
                ("is_equipped", models.BooleanField(default=False)),
                (
                    "equipment_slot",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_quest_item", models.BooleanField(default=False)),
                ("quest_id", models.CharField(blank=True, max_length=64, null=True)),
                ("keyring", models.BooleanField(default=False)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character_id", "is_equipped"],
                        name="world_inven_charact_78c6bc_idx",
                    ),
                    models.Index(
                        fields=["character_id", "keyring"],
                        name="world_inven_charact_603811_idx",
                    ),
                    models.Index(
                        fields=["character_id", "is_quest_item"],
                        name="world_inven_charact_34ba3a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_type", models.CharField(max_length=32)),
                ("amount", models.IntegerField()),
                ("interval_days", models.IntegerField(default=7)),
                ("next_due", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("grace_until", models.DateTimeField(blank=True, null=True)),
                ("lapsed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_payments",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character_id", "payment_type"],
                        name="world_recur_charact_5889d9_idx",
                    ),
                    models.Index(
                        fields=["next_due", "active"],
                        name="world_recur_next_du_87d34c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ZoneAttunement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_id", models.CharField(db_index=True, max_length=64)),
                ("score", models.FloatField(default=0.0)),
                ("last_visited", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_attunements",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "zone_id")},
            },
        ),
    ]
