# Generated by Django 6.0.3 on 2026-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0002_alter_factionstanding_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorldEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                (
                    "zone_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "faction_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                ("character_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("data", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="world_world_event_t_3b8f74_idx",
                    ),
                    models.Index(
                        fields=["zone_id", "occurred_at"],
                        name="world_world_zone_id_b9cf46_idx",
                    ),
                    models.Index(
                        fields=["faction_id", "occurred_at"],
                        name="world_world_faction_c85a35_idx",
                    ),
                ],
            },
        ),
    ]
