# Generated by Django 6.0.3 on 2026-03-27 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0006_knowntopicrecord_characterrecipe"),
        ("world", "0006_spawnrecord"),
    ]

    operations = []
