# Generated by Django 6.0.6 on 2026-07-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0008_rename_mob_template_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_key", models.CharField(max_length=192, unique=True)),
                ("node_type", models.CharField(db_index=True, max_length=32)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "zone_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "settlement_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "faction_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["node_type", "zone_id"],
                        name="world_socia_node_ty_28d7fd_idx",
                    ),
                    models.Index(
                        fields=["node_type", "settlement_id"],
                        name="world_socia_node_ty_ad42d3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edge_key", models.CharField(max_length=240, unique=True)),
                ("edge_type", models.CharField(db_index=True, max_length=64)),
                (
                    "directionality",
                    models.CharField(
                        choices=[
                            ("one_way", "One Way"),
                            ("two_way", "Two Way"),
                            ("broadcast", "Broadcast"),
                            ("gatekept", "Gatekept"),
                        ],
                        default="one_way",
                        max_length=16,
                    ),
                ),
                ("trust", models.FloatField(default=0.5)),
                ("latency_seconds", models.PositiveIntegerField(default=0)),
                ("bandwidth", models.PositiveIntegerField(default=3)),
                ("secrecy", models.CharField(blank=True, default="", max_length=32)),
                ("distortion", models.CharField(blank=True, default="", max_length=32)),
                ("scope_tags", models.JSONField(default=list)),
                ("blockers", models.JSONField(default=list)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_social_edges",
                        to="world.socialnode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_social_edges",
                        to="world.socialnode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("trust__gte", 0.0), ("trust__lte", 1.0)),
                        name="social_edge_trust_probability",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["source_node", "active"],
                        name="world_socia_source__a2f9b5_idx",
                    ),
                    models.Index(
                        fields=["target_node", "active"],
                        name="world_socia_target__44c915_idx",
                    ),
                    models.Index(
                        fields=["edge_type", "active"],
                        name="world_socia_edge_ty_562cfe_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact_key", models.CharField(max_length=192, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("summary", models.TextField()),
                ("tags", models.JSONField(default=list)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("witnessed", "Witnessed"),
                            ("local", "Local"),
                            ("institutional", "Institutional"),
                            ("route", "Route"),
                            ("global", "Global"),
                        ],
                        db_index=True,
                        default="local",
                        max_length=16,
                    ),
                ),
                ("evidence", models.JSONField(default=dict)),
                ("weight", models.FloatField(default=1.0)),
                ("confidence", models.FloatField(default=1.0)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actor_social_facts",
                        to="world.socialnode",
                    ),
                ),
                (
                    "scope_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoped_social_facts",
                        to="world.socialnode",
                    ),
                ),
                (
                    "subject_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_social_facts",
                        to="world.socialnode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0.0), ("confidence__lte", 1.0)
                        ),
                        name="social_fact_confidence_probability",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["subject_node", "visibility"],
                        name="world_socia_subject_bf38cc_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="world_socia_event_t_4730b9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claim_key", models.CharField(max_length=224, unique=True)),
                ("claim_type", models.CharField(db_index=True, max_length=64)),
                ("summary", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("supported", "Supported"),
                            ("rumor", "Rumor"),
                            ("contested", "Contested"),
                            ("false", "False"),
                            ("unknown", "Unknown"),
                        ],
                        default="rumor",
                        max_length=16,
                    ),
                ),
                ("intent", models.CharField(blank=True, default="", max_length=64)),
                ("bias_tags", models.JSONField(default=list)),
                ("confidence", models.FloatField(default=0.5)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "fact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="world.socialfact",
                    ),
                ),
                (
                    "speaker_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spoken_social_claims",
                        to="world.socialnode",
                    ),
                ),
                (
                    "subject_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_social_claims",
                        to="world.socialnode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0.0), ("confidence__lte", 1.0)
                        ),
                        name="social_claim_confidence_probability",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["speaker_node", "claim_type"],
                        name="world_socia_speaker_7a6a97_idx",
                    ),
                    models.Index(
                        fields=["subject_node", "status"],
                        name="world_socia_subject_1b7b73_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowledge_key", models.CharField(max_length=260, unique=True)),
                ("channel", models.CharField(db_index=True, max_length=64)),
                ("confidence", models.FloatField(default=0.5)),
                ("spreading", models.BooleanField(db_index=True, default=False)),
                ("learned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "available_after",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("evidence", models.JSONField(default=dict)),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_by",
                        to="world.socialclaim",
                    ),
                ),
                (
                    "edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carried_social_knowledge",
                        to="world.socialedge",
                    ),
                ),
                (
                    "fact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="known_by",
                        to="world.socialfact",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_knowledge",
                        to="world.socialnode",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sourced_social_knowledge",
                        to="world.socialnode",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(("fact__isnull", False))
                            | models.Q(("claim__isnull", False))
                        ),
                        name="social_knowledge_has_fact_or_claim",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("confidence__gte", 0.0), ("confidence__lte", 1.0)
                        ),
                        name="social_knowledge_confidence_probability",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=["node", "channel"],
                        name="world_socia_node_id_f19c3b_idx",
                    ),
                    models.Index(
                        fields=["node", "spreading"],
                        name="world_socia_node_id_b74495_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialTrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trace_key", models.CharField(max_length=280, unique=True)),
                ("summary", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "edge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_traces",
                        to="world.socialedge",
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_social_traces",
                        to="world.socialnode",
                    ),
                ),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traces",
                        to="world.socialknowledge",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_social_traces",
                        to="world.socialnode",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["to_node", "created_at"],
                        name="world_socia_to_node_e6eecb_idx",
                    ),
                ],
            },
        ),
    ]
