# Generated by Django 6.0.7 on 2026-07-09 19:12

from django.db import migrations, models
from django.db.models import Count


def reconcile_duplicate_standings(apps, schema_editor):
    """Collapse legacy SQLite duplicates before portable constraints land.

    PostgreSQL enforced the previous ``nulls_distinct=False`` constraint, but
    SQLite ignored it. Keep the oldest row identity, copy the newest snapshot,
    and preserve any betrayal flag set across the duplicate records.
    """

    FactionStanding = apps.get_model("world", "FactionStanding")
    duplicate_groups = (
        FactionStanding.objects.values(
            "character_id",
            "faction_id",
            "subfaction_id",
        )
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )

    for group in duplicate_groups.iterator():
        group_filter = {
            "character_id": group["character_id"],
            "faction_id": group["faction_id"],
            "subfaction_id": group["subfaction_id"],
        }
        rows = FactionStanding.objects.filter(**group_filter)
        keeper = rows.order_by("pk").first()
        latest = rows.order_by("-last_updated", "-pk").first()
        betrayal_flag = rows.filter(betrayal_flag=True).exists()

        FactionStanding.objects.filter(pk=keeper.pk).update(
            standing=latest.standing,
            trust=latest.trust,
            betrayal_flag=betrayal_flag,
            last_updated=latest.last_updated,
        )
        rows.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0009_social_web_kernel"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="factionstanding",
            name="unique_faction_standing",
        ),
        migrations.RenameIndex(
            model_name="characterquest",
            new_name="world_cq_char_status_idx",
            old_name="world_chara_charact_quest_status_idx",
        ),
        migrations.RenameIndex(
            model_name="characterquest",
            new_name="world_cq_char_quest_idx",
            old_name="world_chara_charact_quest_id_idx",
        ),
        migrations.AlterField(
            model_name="characterability",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterguild",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterquest",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="characterrecipe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="knowntopicrecord",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RunPython(
            reconcile_duplicate_standings,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="factionstanding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subfaction_id__isnull", True)),
                fields=("character", "faction_id"),
                name="unique_top_faction_standing",
            ),
        ),
        migrations.AddConstraint(
            model_name="factionstanding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subfaction_id__isnull", False)),
                fields=("character", "faction_id", "subfaction_id"),
                name="unique_subfaction_standing",
            ),
        ),
    ]
