# Generated by Django 5.1.6 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0019_social_visibility_and_edge_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialknowledge",
            name="last_dispatched_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
