# Generated by Django 5.1.6 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0020_social_knowledge_dispatch_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialTopologyBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("zone_id", models.CharField(db_index=True, max_length=64)),
                ("kind", models.CharField(choices=[("node", "Node"), ("edge", "Edge")], max_length=8)),
                ("object_key", models.CharField(max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["zone_id", "kind"], name="world_soc_zone_id_5d8f0e_idx"),
                    models.Index(fields=["kind", "object_key"], name="world_soc_kind_2bcf89_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("zone_id", "kind", "object_key"), name="social_topology_binding_unique_owner"),
                ],
            },
        ),
    ]
