# Generated by Django 5.1.6 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0021_social_topology_binding"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncounterReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corpse_id", models.BigIntegerField(db_index=True)),
                ("source_mob_key", models.CharField(max_length=128)),
                ("item_definitions", models.JSONField(default=list)),
                ("scales", models.IntegerField(default=0)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounter_rewards",
                        to="objects.objectdb",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["character", "claimed_at"],
                        name="world_reward_claim_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("character", "corpse_id"),
                        name="unique_personal_encounter_reward",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("scales__gte", 0)),
                        name="encounter_reward_scales_nonnegative",
                    ),
                ],
            },
        ),
    ]
