# Generated by Django 6.0.3 on 2026-03-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0013_defaultobject_alter_objectdb_id_defaultcharacter_and_more"),
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="factionstanding",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="factionstanding",
            constraint=models.UniqueConstraint(
                fields=("character", "faction_id", "subfaction_id"),
                name="unique_faction_standing",
                nulls_distinct=False,
            ),
        ),
    ]
